## **Perceiving Python programming paradigms 👀**

Early each year, TIOBE announces its Programming Language of The Year. When its latest annual [TIOBE index](https://www.tiobe.com/tiobe-index//programming-languages-definition/) report came out, I was not at all surprised to see [Python again winning the title](https://www.tiobe.com/tiobe-index/python/), which was based on capturing the most search engine ranking points (especially on Google, Bing, Yahoo, Wikipedia, Amazon, YouTube, and Baidu) in 2018.


<p align="center"><img src="https://opensource.com/sites/default/files/uploads/python_tiobe-index.png" />


Adding weight to TIOBE's findings, earlier this year, nearly 90,000 developers took Stack Overflow's annual [Developer Survey](https://insights.stackoverflow.com/survey/2019), which is the largest and most comprehensive survey of people who code around the world. The main takeaway from this year's results was:

"Python, the fastest-growing major programming language, has risen in the ranks of programming languages in our survey yet again, edging out Java this year and standing as the second most loved language (behind Rust)."

Ever since I started programming and exploring different languages, I have seen admiration for Python soaring high. Since 2003, it has consistently been among the top 10 most popular programming languages. As TIOBE's report stated:

```
"It is the most frequently taught first language at universities nowadays, it is number one in the statistical domain,
number one in AI programming, number one in scripting and number one in writing system tests.
Besides this, Python is also leading in web programming and scientific computing (just to name some other domains).
In summary, Python is everywhere."
```
There are several reasons for Python's rapid rise, bloom, and dominance in multiple domains, including web development, scientific computing, testing, data science, machine learning, and more. The reasons include its

* Readable and maintainable code
* Extensive support for third-party integrations and libraries
* Modular, dynamic, and portable structure
* Flexible programming; learning ease and support
* User-friendly data structures
* productivity and speed and, most important, community support.

The diverse application of Python is a result of its combined features, which give it an edge over other languages.


### **Reference** :

[opensource - python programming paradigms](https://opensource.com/article/19/10/python-programming-paradigms)

## **Introduction to Python 🐍**

**Interpreter** : Translates program one statement at a time.	<br/>
**Compiler** : Scans the entire program and translates it as a whole into machine code.

In various books of python programming, it is mentioned that python language is interpreted. But that is half correct the python program is first compiled and then interpreted. The compilation part is hidden from the programmer thus, many programmers believe that it is an interpreted language. The compilation part is done first when we execute our code and this will generate byte code and internally this byte code gets converted by the python virtual machine(p.v.m) according to the underlying platform(machine+operating system).

Now the question is – if there is any proof that python first compiles the program internally and then run the code via interpreter?
The answer is yes! and note this compiled part is get deleted by the python(as soon as you execute your code) just it does not want programmers to get into complexity.

<p align="center"><img src="https://indianpythonista.files.wordpress.com/2018/01/pjme67t.png" width="50%"/></p>


### **Reference**

* [https://indianpythonista.files.wordpress.com/2018/01/pjme67t.png](https://indianpythonista.files.wordpress.com/2018/01/pjme67t.png)

```
Python supports four main programming paradigms: imperative, functional, procedural, and object-oriented.
```

The conept of imperative programming, functional programming, procedural programming, and object-oriented programming explained in detail.

## **Data types in Python**


Every value in Python has a datatype. Since everything is an object in Python programming, data types are actually classes and variables are instance (object) of these classes.

Datatypes in python
* int
* float
* string
* bool
* set
* tuple
* dict

We can use the type() function to know which class a variable or a value belongs to. Similarly, the isinstance() function is used to check if an object belongs to a particular class.

## **Python Number**

In [ ]:
a = 5
print(a, "is of type", type(a))

a = 2.0
print(a, "is of type", type(a))

a = 1+2j
print(a, "is of type", type(a))

# The isinstance() function returns True if the specified object is of the specified type, otherwise False
print(a, "is complex number?", isinstance(1+2j,complex))

5 is of type <class 'int'>
2.0 is of type <class 'float'>
(1+2j) is of type <class 'complex'>
(1+2j) is complex number? True


```
When converting a bool to an int, the integer value is always 0 or 1,
but when converting an int to a bool, the boolean value is True for all integers except 0.
```

```python
>>> int(False)
0
>>> int(True)
1
>>> bool(5)
True
>>> bool(-5)
True
>>> bool(0)
False
```

In [ ]:
# integer equivalent of binary number 101
num = 0b101
print(num)

# integer equivalent of Octal number 32
num2 = 0o32
print(num2)

# integer equivalent of Hexadecimal number FF
num3 = 0xFF
print(num3)

5
26
255


In [ ]:
# In python 3

# Boolean 'True' is interpreted as 1
# Boolean 'False' is interpreted as 0

print(1 + True)
print(1 - False)

2
1


In [ ]:
# type

print(type(name))

<class 'str'>


In [ ]:
# Type conversion from string to int
weight = input("what is weight ")
final = int(weight)*0.45
print(final)

what is weight 45
20.25


## **String**

```
String is sequence of Unicode characters. We can use single quotes or double quotes to represent strings.
Multi-line strings can be denoted using triple quotes, ''' or """.
```
### **Points to remember**

* Just like a list and tuple, the slicing operator [ ] can be used with strings. Strings, however, are immutable.

* A **mutable** type means that the inner value can change, not just what the variable references.

* A **immutable** type means that the inner value can not be change.


In [ ]:
# if we want to use this type of words in sentence -> year's
# then we have to use double quotes " " or \

string = "you're awesome"
print(string)

string2 = 'I\'m John Robert'
print(string2)

# if want to assign "important msg" like this we have to use single quote  ''
str = 'im "Hritik"'
print(str)

# for multitline string ''' % ''' for sending mail

mail = '''
        Hii buddy

        im Hritik

        you look awesome

        thank you,
 '''

print(mail)

'''
In python, the string data types are immutable. Which means a string value cannot be updated.
We can verify this by trying to update a part of the string which will led us to an error.
'''

# Generates error
# Strings are immutable in Python
# string[5] ='d'

you're awesome
I'm John Robert
im "Hritik"

        Hii buddy 

        im Hritik 

        you look awesome 

        thank you,
 


### **Access characters in a string**

We can access individual characters using **`indexing`** and a range of characters using slicing. Index starts from 0. <br/>

Trying to access a character out of index range will raise an **`IndexError`**. The index must be an integer. We can't use floats or other types, this will result into **`TypeError`**.

Python allows negative indexing for its sequences.

The index of -1 refers to the last item, -2 to the second last item and so on. We can access a range of items in a string by using the slicing operator :(colon).

In [ ]:
# Accessing string characters in Python
str = 'Programiz'
print('str = ', str)

# first character
print('str[0] = ', str[0])

# last character
print('str[-1] = ', str[-1])

# slicing 2nd to 5th character
print('str[1:5] = ', str[1:5])

# slicing 6th to 2nd last character
print('str[5:-2] = ', str[5:-2])

str =  Programiz
str[0] =  P
str[-1] =  z
str[1:5] =  rogr
str[5:-2] =  am


Slicing can be best visualized by considering the index to be between the elements as shown below.

If we want to access a range, we need the index that will slice the portion from the string.


<p align="center"><img src ="https://www.nltk.org/images/string-slicing.png" width="80%"/></p>


### **Remember**

```
Strings are immutable.
```
This means that elements of a string cannot be changed once they have been assigned. <br/>

We can simply reassign different strings to the same name.

However, lists are mutable, and their contents can be modified at any time. As a result, lists support operations that modify the original value rather than producing a new value.

( Concept of List is explained in detail in the below few section)

```python
>>> my_string = 'programiz'
>>> my_string[5] = 'a'
...
TypeError: 'str' object does not support item assignment
>>> my_string = 'Python'
>>> my_string
```

We cannot delete or remove characters from a string. But deleting the string entirely is possible using the del keyword.

```python
>>> del my_string[1]
...
TypeError: 'str' object doesn't support item deletion
>>> del my_string
>>> my_string
...
NameError: name 'my_string' is not defined
```

In [ ]:
str1 = "first"
print(id(str1))

str1 = str1+ "Two"
print(id(str1))

140303069318592
140302495689712


```
Earlier str1 was pointing to memory address 140303069318592 now, it’s pointing to 140302495689712
which means Python, update the id of same variable containing different string.
```


### **Concatenation of Two or More Strings**

Joining of two or more strings into a single one is called concatenation.

The + operator does this in Python. Simply writing two string literals together also concatenates them.

The * operator can be used to repeat the string for a given number of times.

When we run the above program, we get the following output:

```python
str1 + str2 =  HelloWorld!
str1 * 3 = HelloHelloHello
```
Writing two string literals together also concatenates them like + operator.

If we want to concatenate strings in different lines, we can use parentheses.

```python
>>> # two string literals together
>>> 'Hello ''World!'
'Hello World!'

>>> # using parentheses
>>> s = ('Hello '
...      'World')
>>> s
'Hello World'
```

In [ ]:
# Python String Operations
str1 = 'Hello'
str2 ='World!'

# using +
print('str1 + str2 = ', str1 + str2)

# using *
print('str1 * 3 =', str1 * 3)

str1 + str2 =  HelloWorld!
str1 * 3 = HelloHelloHello


## **List**

*List* is an ordered sequence of items. It is one of the most used datatype in Python and is very flexible. All the items in a list do not need to be of the same type.

There are a few things we typically want to do with lists:

* retrieve (or set) an item at a specific position via indexing
* check for membership (e.g. does b_list contain the number 2?)
* concatenate two lists together
* get the length of the list
* add an item to the list
* remove an item from the list

In [ ]:
words = ['green', 'blue', 'red']
print(words[0])

words[2] = 'orange'
print(words)

green
['green', 'blue', 'orange']


In [ ]:
# Concatenating Lists

a_list = [1, 2, 3, 4]
b_list = ['cinco', 'six', 'VII']
print(a_list + b_list)

[1, 2, 3, 4, 'cinco', 'six', 'VII']


In [ ]:
# List slicing
'''
List slicing works for both int array and string
'''
a = [5,10,15,20,25,30,35,40]

# a[2] = 15
print("a[2] = ", a[2])

# a[0:3] = [5, 10, 15]
print("a[0:3] = ", a[0:3])

# a[5:] = [30, 35, 40]
print("a[5:] = ", a[5:])

a[2] =  15
a[0:3] =  [5, 10, 15]
a[5:] =  [30, 35, 40]


In [ ]:
course = 'python for beginners'

# Display 1st element of string
print("course[0] : ",course[0])

# Print in last element of string
print("course[-1] : ",course[-1])

# Print in 2nd last element of string
print("course[-2] : ",course[-2])

# display all elements
'''
Usecase : create a duplicate array with same length
'''
print("course[:] : ",course[:])

course[0] :  p
course[-1] :  s
course[-2] :  r
course[:] :  python for beginners


In [ ]:
# List slicing ( start : end : increment )
'''
By default increment is 1
'''

# start from 0 till end
print("course[0:] : ",course[0:])

# start from 0th index and end at 4th index (Exclude 5)
print("course[:5] : ",course[:5])

# start from 0th index and end at 4th index
print("course[0:5] : ",course[0:5])

# start from 1st index to 2nd index
print("course[1:3] : ",course[1:3]) # exclude 3 only takes 1,2

# start from 1st index and end at 2nd last element
print("course[1:-1] : ",course[1:-1]) # exclude -1

course[0:] :  python for beginners
course[:5] :  pytho
course[0:5] :  pytho
course[1:3] :  yt
course[1:-1] :  ython for beginner


In [ ]:
arr = [2,3,6,4,5,8,10,1]

# print from 2nd element till end
print("arr[2::] : ",arr[2::])

# print from 2nd element till 5th (exclude 6) and increment by 1
print("arr[2:6:] : ",arr[2:6:])

# print from 2nd element till end and increment by 2
print("arr[2::2] : ",arr[2::2])


# print from 2nd element till 8 and increment by 2
print("arr[2:6:2] : ",arr[2:6:2])

# print reverse list
'''
Default start = 0 and increment = 1
'''
print("arr[::-1] : ",arr[::-1])  ## (start : end : increment)

arr[2::] :  [6, 4, 5, 8, 10, 1]
arr[2:6:] :  [6, 4, 5, 8]
arr[2::2] :  [6, 5, 10]
arr[2:6:2] :  [6, 5]
arr[::-1] :  [1, 10, 8, 5, 4, 6, 3, 2]


List methods are present below in [Inbuilt - Function](#Inbuilt-Function)

## **Mutability in Python**

Lists are the first Python type that we’ve seen that is “mutable.” A  mutable type means that the inner value can change, not just what the variable references. This can be a confusing concept so let’s dive a bit into it:

When we assign a scalar value like x = 7 we are essentially saying that x now has the value 7 until we say otherwise. If we then say y = x we are saying y is 7 too. If we change x later, y does not also change. Here’s a demonstration:

```python
>>> x = 7
>>> y = x
>>> print('x =', x, '    y =', y)
x = 7      y = 7

>>> x = 8
>>> print('x =', x, '    y =', y)
x = 8      y = 7

>>> y = 9
>>> print('x =', x, '    y =', y)
x = 8      y = 9
```

Notice that x and y change independently of one another. This is also true if we do it with any of the other scalar types from Part 1 (str, float, bool, etc.)

We can change what value a variable points to as many times as we like:
```python
x = 7, x = "hello", x = 3.14, etc.
```

Lists offer a different option. If we set x to a list, we can also change the make-up of the list:

```python
>>> x = [1, 2, 3]
>>> y = x
>>> print('x =', x, '       y =', y)
x = [1, 2, 3]        y = [1, 2, 3]

>>> x.append(4)
>>> print('x =', x, '    y =', y)
x = [1, 2, 3, 4]     y = [1, 2, 3, 4]
Wait.. what?! y changed when x changed?
```

What is the difference between this and the above? Why are x and y now linked?

Let’s explore...

```python
>>> x = [1, 2, 3]
>>> y = x
>>> z = x
>>> print('x=', x, '       y=', y, '        z=', z)
x= [1, 2, 3]        y= [1, 2, 3]         z= [1, 2, 3]


>>> # append 4 to x, it will also appear in y and z
>>> x.append(4)
>>> print('x=', x, '    y=', y, '     z=', z)
x= [1, 2, 3, 4]     y= [1, 2, 3, 4]      z= [1, 2, 3, 4]

>>> # ok at this point all three have changed, let's assign to x now
>>> x = [0, 0, 0]
>>> print('x=', x, '       y=', y, '     z=', z)
x= [0, 0, 0]        y= [1, 2, 3, 4]      z= [1, 2, 3, 4]

# wait... that time it only changed x?
```

If the above isn’t making sense to you that’s fine. Let’s think about what we know though:

In our first example with the integers, any time we set x = or y = it didn’t affect the other one.

In our second example, when we called x.append we know that y changed too.

In our third example, when we set **`x = [0, 0, 0]`** those changes didn’t affect y or z.

The common thread here is the = operator. When we set x to a new value, whether it is an int or list (or anything else)- we are creating a new value. When we call a method like x.append(4) though, we are not creating a new value but instead modifying (mutating) the underlying array we created when we said **`x = [1, 2, 3]`**.

It can take some getting used to but there’s a separation between the concept of a value and a variable.

Whenever we define a variable by typing an int, str, float, or list directly (what we call a literal) we’re doing the same thing, regardless of what type we’re using:

**`x = [1, 2, 3]`** creates a new list with the value **`[1, 2, 3]`** and points x at it.

y = "hello" creates a new string with the value “hello” and points y at it.

When we assign from one variable to another the behavior varies slightly though:

**`x = y`** when **`y`** is immutable means that **`x`** now has a copy of the value of **`y`**.

**`x = y`** when **`y`** is mutable means that **`x`** is a reference to the same value as **`x`**.

This is why we have the ability to modify our list in the above examples, but when we assign a new value to x the other values do not update.

```

x = 7

variables                  values

x   --------------------->  7
y = x

variables                  values

x   --------------------->  7
y   --------------------->  7
a = [1, 2, 3]

variables                  values

x   --------------------->  7
y   --------------------->  7
a   --------------------->  [1, 2, 3]
b = a

variables                  values

x   --------------------->  7
y   --------------------->  7
a   --------------------->  [1, 2, 3]
b   ----------/
a.append(4)

variables                  values

x   --------------------->  7
y   --------------------->  7
a   --------------------->  [1, 2, 3, 4]
b   ----------/
a = []

variables                  values

x   --------------------->  7
y   --------------------->  7
a   --------------------->  []
b   --------------------->  [1, 2, 3, 4]
b = None

variables                  values

x   --------------------->  7
y   --------------------->  7
a   --------------------->  []
b   --------------------->  None
                            [1, 2, 3, 4] *will be deleted*
```

**Reference** :

* [https://jpt-pynotes.readthedocs.io/en/latest/more-types.html](https://jpt-pynotes.readthedocs.io/en/latest/more-types.html)


## **tuple**

Tuple is an ordered sequence of items same as a list. The only difference is that tuples are immutable. Tuples once created cannot be modified.

Tuples are used to write-protect data and are usually faster than lists as they cannot change dynamically.

tuple -> we can not append , remove , pop , insert , u can not modify your list.

only thing u can do -> count , index a item in list

```
The main diffrence between tuple and list is :- tuple is immutable and list is mutable
```
that mean we can not change tuple value by modifying it but in list we can do that.

### **`Note`**

Another thing to note is that strictly speaking, the comma is what makes the tuple, not the parentheses. In practice it is a good idea to include the parentheses for clarity and because they are needed in some situations to make operator precedence clear.

Let’s look at a quick example:

```python
>>> a_tuple = (1, 2, 3)
>>> another_tuple = 1, 2, 3
>>> a_tuple == b_tuple
True
This is also important if you need to make a single element tuple:

>>> x = ('one')
>>> y = ('one',)
>>> type(x)
str
>>> type(y)
tuple
```

In [ ]:
a = (1,2,3)
b = 1,2,3
print(type(b))
print(a==b)

<class 'tuple'>
True


In [ ]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [ ]:
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

banana


In [ ]:
thistuple = ("apple", "banana", "cherry")
print(thistuple[-1])

cherry


In [ ]:
# Range of Indexes
# You can specify a range of indexes by specifying where to start and where to end the range.
# Return the third, fourth, and fifth item:

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

('cherry', 'orange', 'kiwi')


In [ ]:
# Negative indexing means starting from the end of the tuple.

# This example returns the items from index -4 (included) to index -1 (excluded)

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1])

('orange', 'kiwi', 'melon')


In [ ]:
# Change Tuple Values
'''
Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.

But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.
'''

x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


In [ ]:
# Iterate through the items and print the values:

thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

apple
banana
cherry


In [ ]:
# To determine if a specified item is present in a tuple use the in keyword

thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

Yes, 'apple' is in the fruits tuple


In [ ]:
# To determine how many items a tuple has, use the len() method

thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

3


In [ ]:
# Once a tuple is created, you cannot add items to it. Tuples are unchangeable.
'''

thistuple = ("apple", "banana", "cherry")
thistuple[3] = "orange" # This will raise an error
print(thistuple)

'''

##  **Set**

A set is an unordered, mutable collection. Set is an unordered and unindexed collection of items in Python. Unordered means when we display the elements of a set, it will come out in a random order. Unindexed means, we cannot access the elements of a set using the indexes like we can do in list and tuples.

Set is an unordered collection of unique items. Set is defined by values separated by comma inside braces { }. Items in a set are not ordered.

You cannot access items in a set by referring to an index, since sets are unordered the items has no index.


We can perform set operations like union, intersection on two sets.
* Sets have unique values. <br/>
* They eliminate duplicates.


In [ ]:
a = {5,2,3,1,4}

# printing set variable
print("a = ", a)

# data type of variable a
print(type(a))

a =  {1, 2, 3, 4, 5}
<class 'set'>


In [ ]:
# Create an empty set

s = set()
print(f'type of s is : {type(s)}')

type of s is : <class 'set'>


In [ ]:
# display unique value

# 1st way without using set() function
{1,1,4,2,2,5}

{1, 2, 4, 5}

In [ ]:
# 2nd way with using set() function
set([1,2,4,4,8,8,4])

{1, 2, 4, 8}

In [ ]:
# set | add() method
# We can add item into the set
thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

# add value to the set
s = {1,2,3}
s.add(5)
print(s)

{'orange', 'apple', 'cherry', 'banana'}
{1, 2, 3, 5}


In [ ]:
# set | update() method
# We can update item into the set
thisset = {"apple", "banana", "cherry"}

thisset.update(["orange", "mango", "grapes"])

print(thisset)

{'cherry', 'apple', 'banana', 'orange', 'grapes', 'mango'}


In [ ]:
# set | Remove() method
'''
This operation removes element  from the set.
If element  does not exist, it raises a KeyError.
The .remove(x) operation returns None.

'''
s1 = set([1, 2, 3, 4, 5, 6, 7, 8, 9])
s1.remove(5)
print(s1)

# Return None
set([1, 2, 3, 4, 6, 7, 8, 9])
print(s1.remove(4))
print(s1)

{1, 2, 3, 4, 6, 7, 8, 9}
None
{1, 2, 3, 6, 7, 8, 9}


In [ ]:
# If element does not exist in the set , then it raises KeyError
'''
s2 = set([1, 2, 3, 6, 7, 8, 9])
s2.remove(0)
KeyError: 0
'''

In [ ]:
# set | pop() method
'''
This operation removes and return an arbitrary element from the set.
If there are no elements to remove, it raises a KeyError.
'''

s3 = set([1,2])
# 1st pop
print(s3.pop())
print(s3)

# 2nd pop
print(s3.pop())
print(s3)

# Now set is empty
# if we try pop then it raises a KeyError

1
{2}
2
set()


In [ ]:
# set | clear() in python

'''
The clear() method removes all elements from the set.

parameters:
  The clear() method doesn't take any parameters.
Return:
  The clear() method doesn't return any value.

'''
# set of letters
set1 = {6, 0, 4, 1}
print('set1 before clear:', set1)

# clearing vowels
set1.clear()
print('set1 after clear:', set1)

set1 before clear: {0, 1, 4, 6}
set1 after clear: set()


In [ ]:
# set | copy() function
'''
Parameters:The copy() method for sets doesn’t take any parameters.

Return value:The function returns a shallow copy of the original set.
'''
# Python program to demonstrate that copy , created using set copy is shallow

first = {1,2,3,4,5}
second = first.copy()

# before adding
print('before adding: ')
print('first: ',first)
print('second: ', second)

# Adding element to second, first does not change.
second.add(7)

# after adding
print('after adding: ')
print('first: ',first)
print('second: ', second)

before adding: 
first:  {1, 2, 3, 4, 5}
second:  {1, 2, 3, 4, 5}
after adding: 
first:  {1, 2, 3, 4, 5}
second:  {1, 2, 3, 4, 5, 7}


In [ ]:
my_set = {1,2,3,4,5}
your_set = {4,5,6,7,8,9,10}


# difference(x) : Returns a set containing the difference between two or more sets
print(my_set.difference(your_set))
print(my_set)

# discard(x) : This operation also removes element x from the set
'''
Question : Then what is the difference between remove and discard ?

Answer : If element x does not exist, it does not raise a KeyError.
The .discard(x) operation returns None.
'''
print(your_set.discard(10))
print(your_set)

# difference_update(x) : Removes the items in this set that are also included in another, specified set
print(my_set.difference_update(your_set))
print(my_set)

# intersection(x) : Returns a set, that is the intersection of two other sets
print(my_set.intersection(your_set))
print(my_set)

# isdisjoint(x) : Returns whether two sets have a intersection or not
print(my_set.isdisjoint(your_set))
print(my_set)

# union
print(my_set.union(your_set))

# issubset(x)	Returns whether another set contains this set or not
print(my_set.issubset(your_set))
print(my_set)

# issuperset(x)	Returns whether this set contains another set or not
print(my_set.issuperset(your_set))
print(my_set)

# intersection_update()	Removes the items in this set that are not present in other, specified set(s)
print(my_set.intersection_update(your_set))
print(my_set)

{1, 2, 3}
{1, 2, 3, 4, 5}
None
{4, 5, 6, 7, 8, 9}
None
{1, 2, 3}
set()
{1, 2, 3}
True
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
False
{1, 2, 3}
False
{1, 2, 3}
None
set()


In [ ]:
x = {"a", "b", "c"}
y = {"f", "d", "a"}
z = {"c", "d", "e"}

result = x.union(y, z)

print(result)

{'d', 'c', 'a', 'e', 'f', 'b'}


In [ ]:
# Transfer value of y to e and then print it
y = [9,8,3,6,4,4,5,6,7]
e = set()

for i in y:
  e.add(i)

print(list(e))

[3, 4, 5, 6, 7, 8, 9]


Since, set are unordered collection, indexing has no meaning. Hence, the slicing operator [ ] does not work.

```python

>>> a = {1,2,3}
>>> a[1]
Traceback (most recent call last):
  File "<string>", line 301, in runcode
  File "<interactive input>", line 1, in <module>
TypeError: 'set' object does not support indexing

```

## **Dictionaries**

A dictionary is a collection which is ~**`unordered`**~ **`ordered`**, **`changeable`** and **`indexed`**. In Python dictionaries are written with curly brackets, and they have keys and values.

```
Note : I've cross the unordered word, because in python version > 3.6.0, dictionary are ordered previously in
version < 3.6.0 , dictionary was unordered
```

The details explanation is given at the end of this section.

### **`Creating Python Dictionary`**

Creating a dictionary is as simple as placing items inside curly braces **`{}`** separated by commas.

An item has a key and a corresponding value that is expressed as a pair **`(key: value)`**.

While the values can be of any data type and can repeat, keys must be of immutable type (string, number or tuple with immutable elements) and must be unique.


In [ ]:
# empty dictionary
my_dict = {}

# dictionary with integer keys
my_dict = {1: 'apple', 2: 'ball'}

# dictionary with mixed keys
my_dict = {'name': 'John', 1: [2, 4, 3]}
print("my_dict : ", type(my_dict))

# using dict()
my_dict = dict({1:'apple', 2:'ball'})
print("my_dict : ", type(my_dict))

# from sequence having each item as a pair
my_dict = dict([(1,'apple'), (2,'ball')])

my_dict :  <class 'dict'>
my_dict :  <class 'dict'>


In [ ]:
my_dict = {
            'fruits': ['apples', 'oranges'],
            'vegetables': ['carrots', 'peas']
          }
print(my_dict)

{'fruits': ['apples', 'oranges'], 'vegetables': ['carrots', 'peas']}


### **`Accessing Elements from Dictionary`**

  While indexing is used with other data types to access values, a dictionary uses keys.

  Keys can be used either inside square brackets **`[ ]`** or with the **`get()`** method.

  If we use the square brackets **`[  ]`**, KeyError is raised in case a key is not found in the dictionary.

On the other hand
```
the get() method returns None if the key is not found.
```

In [ ]:
# Dictionaries -> contain key - value pairs

people = {
    "name" :"Hritik Jaiswal",
    "age" : 19,
    "is_male" : True,
    "Fav_number":[5,10,15 ]
}

# you can not write like -> print(people["Name"])

print(people["name"])

# We can use GET method to take key-value pair if its not present then
# It will temporely add that into dict and display value related that key

print(people.get("birth","Jan 15 1889"))

# None -> is the object that represent absence of the key
print(people.get("gender"))

people["name"] = "John martin"  # modify name
print(people.get("name"))

Hritik Jaiswal
Jan 15 1889
None
John martin


If you've little bit of programming knowledge then i think you already know, how for loop works.
```
As if now, just understand the purpose of using for loop.
```

In [ ]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

for x in thisdict:
  print("key : " , x)

print("-----------------")
for x in thisdict:
  print("value : ", thisdict[x])

key :  brand
key :  model
key :  year
-----------------
value :  Ford
value :  Mustang
value :  1964


In [ ]:
user = {
    'username' : 'john',
    'password' : 123,
    'email': 'john@gmail.com'
}

for i in user.items():
  print(i)

print("------------------------")

# Tuple unpacking
for key,value in user.items():
  print(key,value)

print("------------------------")

for i in user.keys():
  print(i)
print("------------------------")

for i in user.values():
  print(i)

('username', 'john')
('password', 123)
('email', 'john@gmail.com')
------------------------
username john
password 123
email john@gmail.com
------------------------
username
password
email
------------------------
john
123
john@gmail.com


In [ ]:
# update() : Insert an item to the dictionary
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.update({"color": "White"})

print(car)

# The pop() method removes the item with the specified key name

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print(thisdict.pop("model"))   # return the value of pop element
print(thisdict)

# The popitem() method removes the last inserted item (in versions before 3.7, a random item is removed instead):

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.popitem()
print(thisdict)

# The clear() method empties the dictionary

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

thisdict.clear()
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'White'}
Mustang
{'brand': 'Ford', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang'}
{}


In [ ]:
# Create an empty dict and assign a value

d = {}

iterable = [('a','b'),('1','2'),('c','4')]

for k,v in iterable:
  print(k,v)
  d[k] = v

print(d)

a b
1 2
c 4
{'a': 'b', '1': '2', 'c': '4'}


In [ ]:
# Excersice

'''
input : 1234
output : one two three four
'''

phone =  input("phone : ")

dict  = {
    "1" :"One",
    "2":"Two",
    "3" :"Three",
    "4" :"Four",
    "5" :"Five",
    "6" :"Six",
    "7" :"Seven",
    "8" :"Eight",
    "9" :"Nine",
    "0" :"zero",
}
output = ""
for i in phone:

    output += (dict.get(i,"?")) + " "
    print(i)
print(output)

phone : 105
1
0
5
One zero Five 


In [ ]:
#excerisce -> opposite
words = ["one", "two","three","four","five","six", "seven","eight","nine","zero"]

word = input("Enter the word : ")
mapping  = {
    "one":"1",
    "two":"2",
    "three":"3",
    "four":"4",
    "five":"5",
    "six":"6",
    "seven":"7",
    "eight":"8",
    "nine":"9",
    "zero":"0"
}
spliting = word.split()
print(spliting)
for i in spliting:
    print(mapping.get(i,"&"))



Enter the word : one seven two
['one', 'seven', 'two']
1
7
2


In [ ]:
#excersice -> print emoji
message = input(">")
words= message.split()
emoji = {
    ":)" :"😄",
    ":(" :"😔"
}
output = ""
for i in words:
    output += emoji.get(i,i) + " "

print(output)

>good morning :)
good morning 😄 


```
Since the python dictionary is unordered, so to preserve it's order. we can use OrderedDict
```

---
### **OrderedDict**
---
An OrderedDict is a dictionary subclass that remembers the order that keys were first inserted. The only difference between dict() and OrderedDict() is that:

OrderedDict preserves the order in which the keys are inserted. A regular dict doesn’t track the insertion order, and iterating it gives the values in an arbitrary order. By contrast, the order the items are inserted is remembered by OrderedDict.


In [ ]:
# A Python program to demonstrate working of OrderedDict
from collections import OrderedDict

print("This is a Dict:\n")
d = {}
d['a'] = 1
d['b'] = 2
d['c'] = 3
d['d'] = 4

for key, value in d.items():
    print(key, value)

print("\nThis is an Ordered Dict:\n")
od = OrderedDict()
od['a'] = 1
od['b'] = 2
od['c'] = 3
od['d'] = 4

for key, value in od.items():
    print(key, value)

This is a Dict:

a 1
b 2
c 3
d 4

This is an Ordered Dict:

a 1
b 2
c 3
d 4


Important Points:
```
Key value Change: If the value of a certain key is changed, the position of the key remains unchanged in OrderedDict.
```

In [ ]:
# A Python program to demonstrate working of key
# value change in OrderedDict
from collections import OrderedDict

print("Before:\n")
od = OrderedDict()
od['a'] = 1
od['b'] = 2
od['c'] = 3
od['d'] = 4
for key, value in od.items():
	print(key, value)

print("\nAfter:\n")
od['c'] = 5
for key, value in od.items():
	print(key, value)

Before:

a 1
b 2
c 3
d 4

After:

a 1
b 2
c 5
d 4


Deletion and Re-Inserting:
```
Deleting and re-inserting the same key will push it to the back as OrderedDict however maintains the order of insertion.
```

In [ ]:
# A Python program to demonstrate working of deletion
# re-inserion in OrderedDict
from collections import OrderedDict

print("Before deleting:\n")
od = OrderedDict()
od['a'] = 1
od['b'] = 2
od['c'] = 3
od['d'] = 4

for key, value in od.items():
	print(key, value)

print("\nAfter deleting:\n")
od.pop('c')
for key, value in od.items():
	print(key, value)

print("\nAfter re-inserting:\n")
od['c'] = 3
for key, value in od.items():
	print(key, value)

Before deleting:

a 1
b 2
c 3
d 4

After deleting:

a 1
b 2
d 4

After re-inserting:

a 1
b 2
d 4
c 3


**Reference**: [GeeksforGeeks - OrderedDict in Python](https://www.geeksforgeeks.org/ordereddict-in-python/)

### **NOTE : Python Dictionaries Are Now Ordered. But Keep Using OrderedDict.**




Until recently (i.e In Python version < 3.6.0), Python dictionaries did not preserve the order in which items were added to them. For instance, you might type

```python
>> my_dict = {'fruits': ['apples', 'oranges'], 'vegetables': ['carrots', 'peas']}

>> print(my_dict)
{'vegetables': ['carrots', 'peas'], 'fruits': ['apples', 'oranges']}
```

But in python version > 3.6.0  👇

In [ ]:
my_dict = {'fruits': ['apples', 'oranges'], 'vegetables': ['carrots', 'peas']}

print(my_dict)

{'fruits': ['apples', 'oranges'], 'vegetables': ['carrots', 'peas']}


In the above example dictionary is preserved it's order because of python version > 3.6.0

In [ ]:
!python --version

Python 3.6.9


```
Python dict objects now preserve insertion order in the reference CPython implementation
— but relying on that property is risky.
```

If you wanted a dictionary that preserved order, you could use the **`OrderedDict`** class in the standard library module **`collections`**. (As we already discussed)

However, this situation is changing. Standard dict objects preserve order in the reference (CPython) implementations of Python 3.5 and 3.6, and this order-preserving property is becoming a language feature in Python 3.7.



---
You might think that this change makes the OrderedDict class obsolete. However, there are at least two good reasons to continue using OrderedDict.

1. Relying on standard dict objects to preserve order will cause your code to break on versions of CPython earlier than 3.5 and on some alternative implementations of Python 3.5 and 3.6.

2. Using an OrderedDict communicates your intention to rely on the order of items in your dictionary being preserved, both to human readers of your code and to the third-party libraries you call within it.

In fact, some tools that are widely used in data science assume that the order of items in a dict is not significant.

You can read more about it, in the below article <br/>

---

**Reference** : [Gandenberger - ordered-dicts-vs-ordereddict](http://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/)

## **Precedence and Associativity of Operators**

The operator precedence in Python is listed in the following table. It is in descending order (upper group has higher precedence than the lower ones).

| Operator    | Message  |
|:---------: | :------------------:  |
| ( )  | Parentheses |
| **  | Exponenet |
| +x, -x, ~x  | Unary plus, Unary minus, Bitwise NOT |
| /, *, //, %	  | Multiplication, Division, Floor division, Modulus |
| +, -  | Addition, Subtraction |
| <<, >>  | Bitwise shift operators |
| &	 | Bitwise AND |
| ^	 | Bitwise XOR |
| \| | Bitwise OR  |
| ==, !=, >, >=, <, <=, is, is not, in, not in|	Comparisons, Identity, Membership operators |
| not | 	Logical NOT |
| and	|   Logical AND |
| or	|   Logical OR  |

Reference :

* [Programiz : precedence and associative in python ](https://www.programiz.com/python-programming/precedence-associativity#:~:text=For%20example%2C%20multiplication%20has%20higher%20precedence%20than%20subtraction.&text=But%20we%20can%20change%20this,has%20higher%20precedence%20than%20multiplication.&text=The%20operator%20precedence%20in%20Python,precedence%20than%20the%20lower%20ones)

In [ ]:
# Precedence of /, *,+, ()

# Order
'''
  Here precendence of div and mul are same , but according to associative (which follows form left to right)
  then order will be :
   () > (div) > (mul) > (add)
'''
x = 36 / 4 * (3 +  2) * 4 + 2
print(x)

182.0


In [ ]:
# ordering
# () > ** (exponent) > (mul or div) > (add or sub)

exp = 10 + 3*2**2
print(exp)

22


In [ ]:
# Precedence of or & and

# order
'''
 and > or
'''

meal = "fruit"

money = 0

if meal == "fruit" or meal == "sandwich" and money >= 2:
    print("Lunch being delivered")
else:
    print("Can't deliver lunch")

Lunch being delivered


This program runs if block even when money is 0. It does not give us the desired output since the precedence of and is higher than or.

We can get the desired output by using parenthesis () in the following way:

In [ ]:
# Precedence of or & and

# order
'''
 () > and > or
'''

meal = "fruit"

money = 0

if (meal == "fruit" or meal == "sandwich") and money >= 2:
    print("Lunch being delivered")
else:
    print("Can't deliver lunch")

Can't deliver lunch


Associativity of Python Operators

```
We can see in the above table that more than one operator exists in the same group. These operators have the same precedence.

When two operators have the same precedence, associativity helps to determine the order of operations.

Associativity is the order in which an expression is evaluated that has multiple operators of the same precedence.
Almost all the operators have left-to-right associativity.
```
For example, multiplication and floor division have the same precedence. Hence, if both of them are present in an expression, the left one is evaluated first.

In [ ]:
# Left-right associativity
# Output: 3
print(5 * 2 // 3)

# Shows left-right associativity
# Output: 0
print(5 * (2 // 3))

3
0


In [ ]:
a = 20
b = 10
c = 15
d = 5
e = 0

e = (a + b) * c / d       #( 30 * 15 ) / 5
print("Value of (a + b) * c / d is ",  e)

e = ((a + b) * c) / d     # (30 * 15 ) / 5
print("Value of ((a + b) * c) / d is ",  e)

e = (a + b) * (c / d);    # (30) * (15/5)
print("Value of (a + b) * (c / d) is ",  e)

e = a + (b * c) / d;      #  20 + (150/5)
print("Value of a + (b * c) / d is ",  e)

Value of (a + b) * c / d is  90.0
Value of ((a + b) * c) / d is  90.0
Value of (a + b) * (c / d) is  90.0
Value of a + (b * c) / d is  50.0


In [ ]:
## Note: Exponent operator ** has right-to-left associativity in Python.

# Shows the right-left associativity of **
# Output: 512, Since 2**(3**2) = 2**9
print(2 ** 3 ** 2)

# If 2 needs to be exponated fisrt, need to use ()
# Output: 64
print((2 ** 3) ** 2)

512
64


```
  We can see that 2 ** 3 ** 2 is equivalent to 2 ** (3 ** 2)
```

##  **Input**

```
input ( ) : This function first takes the input from the user and then
evaluates the expression, which means Python automatically identifies
whether user entered a string or a number or list. If the input
provided is not correct then either syntax error or exception is raised by python. For example –
```

In [ ]:
# input type string

name = input("what is name ? ")
print('Hii' , name)
print(type(name))

what is name ? Mike
Hii Mike
<class 'str'>


In [ ]:
# To get the input in the form of 'int'
# We have convert 'str' into 'int'

name = input('what is your birthyear ? ')
year = 2019 -int(name);
print(year)

what is your birthdate ? 2000
19


In [ ]:
# char input

string = input("Enter a string : ")
print(string[0])

# string into list of char
print(list(string))

Enter a string : hello
h
['h', 'e', 'l', 'l', 'o']


In [ ]:
# What if we enter the expression instead of any data type

'''
Their is function called "eval" which evalute the expression and gives the output
'''
expr = eval(input("Enter an expression : "))
print(expr)

Enter an expression : 2 + 3**2 + (1-2)
10


In [ ]:
# rstrip(): will remove the white spaces present in the input
# split(): will convert the string into a list
# map(function, iterable) : typecast the list

# Enter input in horizontal form
ar = list(map(int, input().rstrip().split()))
print(ar)

1 4 5 2
[1, 4, 5, 2]


## **Important stuff 🎯**

``` python

>> print(type(10))                 ## output : <class 'int'>
>> print(bool(-3))                 ## output : True
>> print(bool(0))                  ## output : False
>> print(bool(2))                  ## output : True
>> print(type(0xFF))               ## output : <class 'int'>

All our belongs to type -> int

0b or 0B for Binary and base is 2
0o or 0O for Octal and base is 8
0x or 0X for Hexadecimal and base is 16

>>  type(range(5))                 ## output : <class 'range'>

>> x = 100
   y = 50
   print(x and y)                  ## output : 50

   In Python, When we join two non-Boolean values using a and operator, the value of the expression is the second operands

>> y = 10
   x = y += 2
   print(x)                         ## output : Syntax Error (invalid syntax)


>> a = 4                            ## binary : 0100
   b = 11                           ## binary : 1011
   print(a | b)                     ## output : 1111
   print(a >> 2)                    ## output : 1     ( binary : 01)
   print(b >> 2)                    ## output : 2     ( binary : 10)

   Bitwise right shift operator(>>): The a’s and b’s value is moved right by the 2 bits.

>>  a = [10, 20]
    b = a
    b += [30, 40]
    print(a)                        # [10, 20, 30, 40]
    print(b)                        # [10, 20, 30, 40]

    Because since b and a reference to the same object, when we use, Addition assignment += on b, it changes both a and b

>>  a = ['x','y']
    b = a
    b = b + ['z']
    print(a)                        # ['x','y']
    print(b)                        # ['x','y','z']

    Here, we are not using assignment operator, hence as b changes a does not changed.

>>  print('%x, %X' % (15, 15))      # output : f F

    In output formatting, We use type %x and %X to convert decimal number to hexadecimal number on the screen.
    %x produces lowercase output, and %X produces uppercase output.

>> x = float('NaN')
   print('%f, %e, %F, %E' % (x, x, x, x))         # output :  nan, nan, NAN, NAN

>> print('[%c]' % 65)               # output : [A]

  The c conversion type supports character conversion from ASCII code to the character. It also works for the Unicode
```


## **Command Line and Variable Arguments**

```
Till now, we have taken input in python using raw_input() or input() [for integers].
There is another method that uses command line arguments.
The command line arguments must be given whenever we want to give the input before the start of the script,
while on the other hand, raw_input() is used to get the input while the python program / script is running.
```

For example, in the UNIX environment, the arguments **`‘-a’`** and **`‘-l’`** for the ‘ls’ command give different results.

The command line arguments in python can be processed by using either ‘sys’ module or ‘argparse’ module.



---

Suppose we want to calculate sum of two numbers

Program for that will be :

```python
# Python code to demonstrate the use of 'sys' module
# for command line arguments

import sys

# command line arguments are stored in the form
# of list in sys.argv
argumentList = sys.argv
print argumentList

# Print the name of file
print sys.argv[0]

# Print the first argument after the name of file
print sys.argv[1]

# Print the second argument after the name of file
print sys.argv[1]

# add 2 numbers
a = sys.argv[1]
b = sys.argv[2]
print("addition of two number is :" a+b)
```

```sh
$ python addNumber.py 6 2

['addNumber.py',6,2]
addNumber.py
6
2
addition of two number is : 8
```


## **Formating string**


In [ ]:
username = 'johny'
age = 23

# Simple string
print("Hiii " + username + ", you're " + str(age) + ' old')

# Formated string
print(f'Hiii {username}, you\'re {age} old')

Hiii johny, you're 23 old
Hiii johny, you're 23 old


## **Format**

The string format() method formats the given string into a nicer output in Python.

#### **`String format() Parameters`**

format() method takes any number of parameters. But, is divided into two types of parameters:

* Positional parameters - list of parameters that can be accessed with index of parameter inside curly braces {index}

* Keyword parameters - list of parameters of type key=value, that can be accessed with key of parameter inside curly braces {key}

#### **`Return value from String format()`**

The format() method returns the formatted string.

#### **`How String format() works?`**

The format() reads the type of arguments passed to it and formats it according to the format codes defined in the string.


In [ ]:
x = "Hii"
y = 'Hritik'
z = 'Jaiswal'

print(f"sum of string is x + y : {x} {y}")  # using formatted string
print("Hello, {} {}".format(y,z))           # using format function

sum of string is x + y : Hii Hritik
Hello, Hritik Jaiswal


In [ ]:
# default arguments
print("Hello {}, your balance is {:.2f}.".format("Adam", 230.2346))

# positional arguments
print("Hello {0}, your balance is {1}.".format("Adam", 230.2346))

# keyword arguments
print("Hello {name}, your balance is {blc:.2f}.".format(name="Adam", blc=230.2346))

# mixed arguments
print("Hello {0}, your balance is {blc}.".format("Adam", blc=230.2346))

Hello Adam, your balance is 230.23.
Hello Adam, your balance is 230.2346.
Hello Adam, your balance is 230.23.
Hello Adam, your balance is 230.2346.


In [ ]:
## Simple number formatting

# integer arguments
print("The number is:{:d}".format(123))

# float arguments
print("The float number is:{:f}".format(123.4567898))

# octal, binary and hexadecimal format
print("bin: {0:b}, oct: {0:o}, hex: {0:x}".format(12))

The number is:123
The float number is:123.456790
bin: 1100, oct: 14, hex: c


In [ ]:
# Number formatting for signed numbers

# show the + sign
print("{:+f} {:+f}".format(12.23, -12.23))

# show the - sign only
print("{:-f} {:-f}".format(12.23, -12.23))

# show space for + sign
print("{: f} {: f}".format(12.23, -12.23))

+12.230000 -12.230000
12.230000 -12.230000
 12.230000 -12.230000


**Reference** :- [String - Format (Programmiz.com)](https://www.programiz.com/python-programming/methods/string/format)

## **Math function**

In [ ]:
#Math function
# 1) round
x = 6.5
y = 7.66
print(round(x))
print(round(y))

6
8


In [ ]:
## Round Function

b = 13.9423486
print(b)

# without using round function
# their are 2 ways

print("%.2f" % a)
print("{:.2f}".format(a))

# with round function
print("round function : ",round(a,2))

13.9423486
13.95
13.95
round function :  13.95


In [ ]:
# 2) abs -> return positive no.
x = -3.5
print(abs(x))

3.5


In [ ]:
# 3) Mathametical function

import math
pi = 3.142
math.cos((60*pi)/180)

# ceil() method in Python returns ceiling value of x i.e., the smallest integer not less than x.
print(math.ceil(2.9))

# floor() method in Python returns floor of x i.e., the largest integer not greater than x.
print(math.floor(2.9))

3
2


In [ ]:
print("math.floor(-23.11) : ", math.floor(-23.11))
print("math.floor(300.16) : ", math.floor(300.16))
print("math.floor(300.72) : ", math.floor(300.72))

math.floor(-23.11) :  -24
math.floor(300.16) :  300
math.floor(300.72) :  300


In [ ]:
print("math.floor(-23.11) : ", math.ceil(-23.11))
print("math.floor(300.16) : ", math.ceil(300.16))
print("math.floor(300.72) : ", math.ceil(300.72))

math.floor(-23.11) :  -23
math.floor(300.16) :  301
math.floor(300.72) :  301


## **If - Statement**

In [ ]:
# we can use 'and' & 'or' in if statement
a=2
b=3
c=4
if (a<b) and (c>b):
    print('True')
elif (a==b) or (c>a):
    print('Truee')
elif (b>a) and not (b>c):
    print('Trueee')
else:
    print('false')

True


In [ ]:
# Exercise

weight = int(input('Weight :'))
unit = input('(L)bs or (K)g')
if unit.lower()=='l' or unit.upper()=='L':
    c = weight*0.45;
else:
    c = weight/0.45;
print(c)

Weight :45
(L)bs or (K)gv
100.0


In [ ]:
#if statement

x = 5
y = 10

if (x>y):
    print("truee")
elif (x==y):
    print("falsee")
else:
    print("nothing")

print(f"SUM OF X AND Y : {x+y}")


nothing
SUM OF X AND Y : 15


## **Truthy and Falsy**

In Python, True and False are keywords and will always be equal to 1 and 0.

Under normal circumstances in Python 2, and always in Python 3:
```
False object is of type bool, which is a subclass of int
```
```python
object
   |
 int
   |
 bool
```
There are two types of integers:

      1. integer
      2. Boolean

### **Booleans (bool) - [Python3 Doc](https://docs.python.org/3/reference/datamodel.html#index-10)**

These represent the truth values False and True. The two objects representing the values False and True are the only Boolean objects. The Boolean type is a subtype of the integer type, and Boolean values behave like the values 0 and 1, respectively, in almost all contexts, the exception being that when converted to a string, the strings "False" or "True" are returned, respectively.

All values are considered "truthy" except for the following, which are falsy

### *`Falsy`*

- None
- False
- 0
- 0.0
- 0j
- Decimal(0)
- Fraction(0,1)
- **`[]`** Empty dict
- **`{}`** Empty Set
- **`()`** Empty tuple
- **`''`** Empty string
- **`b''`** Empty bytes
- set( )
- Empty range(0)
- Object which
    - **`obj.__ bool__()`** return False
    - **`obj.__ len__()`** return 0

In [ ]:
print("1 + True = ", 1 + True )
print("==============")
print("1 + False = ", 1 + False )

1 + True =  2
1 + False =  1


In [ ]:
# All values (including positive and negative value) considered as True except 0
if -1 or False:
  print("yes")

yes


In [ ]:
if 1 and True:
  print("Executed")

Executed


In [ ]:
if []:
  print("[] is True")
else:
  print("[] is False")

[] is False


In [ ]:
if None:
  print("None is True")
else:
  print("None is False")

None is False


In [ ]:
## Examples

# '' (Empty string) refers to False

username = input("Enter username : ")
password = int(input("Enter password : "))

if username and password:
  print("Hello, {}".format(username))
else:
  print("Empty username provided")

Enter username : 
Enter password : 123
Empty username provided


In [ ]:
print('\033[92m')  # Green color
arr = ['Hello','world'][False]
print(arr)

print('\033[94m')  # Blue color
arr = ['Hello','world'][True]
print(arr)


Hello

world


Let's try this one

In [ ]:
print( 0 == 0.0 )
print( 1 == 1.0 )

print("==============")

print( False == 0.0 )
print( True == 1.0 )

True
True
True
True


In [ ]:
# So can we use 0.0 instead of False or 1.0 instead of True ? let's see

print('\033[92m')  # Green color

arr = ['Hello','world'][0.0]
print(arr)

print('\033[94m')  # Blue color
arr = ['Hello','world'][1.0]
print(arr)

TypeError: ignored

This because list indexing only works with integers, or objects that define a **`__index__`** method



## **`is` vs `==`**

The Equality operator **`(==)`** compares the values of both the operands and checks for value equality.


In [ ]:
# Observe, what's going on

# Here 1 refers to bool(1) => True
print(True == 1)         # True
print("" == 1)           # False
print([] == 1)           # False
print(10 == 10.0)        # True
print([] == [])          # True
print("1" == 1)          # False

True
False
False
True
True


Whereas the **`‘is’`** operator checks whether two variables point to the same object in memory.

Eg : When I was a kid, our neighbors had two twin cats.
Both cats looked seemingly identical—same charcoal fur, same piercing green eyes. Some personality quirks aside, you just couldn’t tell them apart just from looking at them. But of course they were two different cats, two separate beings, even though they looked exactly the same.

The == operator compares by checking for equality:
```
If these cats were Python objects and we’d compare
them with the == operator, we’d get “both cats are equal” as an answer.
```
The is operator, however, compares identities:
```
If we compared our cats with the is operator, we’d get “these are two different cats” as an answer.
```

In [ ]:
# True
print(True is 1)         # False
print("" is 1)           # False
print([] is 1)           # False
print(10 is 10.0)        # False
print([] is [])          # False
print("1" is 1)          # False

False
False
False
False
False
False


In [ ]:
# pointing to different object and in different memory location,
# that means changing 'a' does not affect 'b'

a = [1,2,3]
b = [1,2,3]
print("a == b : {}".format(a==b))   # Care only about values, not the location
print("a is b : {}".format(a is b)) # Doesn't point to same memory location

a == b : True
a is b : False


In [ ]:
# both are different
print(id(a))
print(id(b))

140570679145608
140570810310792


In [ ]:
# So what we actually means by pointing to same object 🤔 ❓

# Let's understand with an example

a = [1,2,3]
b = a

print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [ ]:
# We know this already, what's new in this?
# Yeah, right

# Now see the magic, when we changes a and then b also gets changed
# it means changing 'a', 'b' also get affected.

a[0] = 'Hello'

print(a)
print(b)

['Hello', 2, 3]
['Hello', 2, 3]


In [ ]:
# See both are equal
print(id(a))
print(id(b))

140570678454728
140570678454728


## **Ternary operator**

Ternary operators also known as conditional expressions are operators that evaluate something based on a condition being true or false.

In [ ]:
# pattern

# "value_if_condition_true" if condition else "value_if_condition_false"

is_allowed = True
message = "Authenticate user" if is_allowed==True else "Unauthenticate user"
print(message)

Authenticate user


In [ ]:
is_allowed = False
message = "Authenticate user" if is_allowed==True else "Unauthenticate user"
print(message)

Unauthenticate user


In [ ]:
# Python program to demonstrate ternary operator
a, b = 10, 20

# Use tuple for selecting an item
# (if_test_false,if_test_true)[test]
print( (b, a) [a < b] )

# Use Dictionary for selecting an item
print({True: a, False: b} [a < b])

# lamda is more efficient than above two methods
# because in lambda  we are assure that
# only one expression will be evaluated unlike in
# tuple and Dictionary
print((lambda: b, lambda: a)[a < b]())

10
10
10


### **Reference**

* [geeksforgeeks - ternary operator in python](https://www.geeksforgeeks.org/ternary-operator-in-python/)

## **Bit manipulation**


```
1.  Complement (~)  - Bitwise not
2.  And (&)
3.  Or (|)
4.  Xor (^)
5.  Right shift (>>)
6.  Left shift (<<)
```

In [ ]:
x = 8
print(type(x))

# Binary representation of number 8
y = bin(8)
print(type(y))
print(y)

# replace the trailing 0b from y
y = y.replace('0b','')
print(y)
print(type(y))

<class 'int'>
<class 'str'>
0b1000
1000
<class 'str'>


In [ ]:
# check bit length
print(bin(42)[2:])
print((42).bit_length())

101010
6


In [ ]:
# Comp
# For positive number  9  => the result would be -(9 + 1)
# For negative number -10 => the result would be  (10 - 1)

print("Complement of 9 : ", ~9)
print("Complement of -10 : ", ~-10)

Complement of 9 :  -10
Complement of -10 :  9


In [ ]:
# bitwise operators

a = 6
b = 4

# Print bitwise AND operation
print("a & b =", a & b)

# Print bitwise OR operation
print("a | b =", a | b)

# print bitwise XOR operation
print("a ^ b =", a ^ b)

a & b = 4
a | b = 6
a ^ b = 2


In [ ]:
# This operator seems useless, unless untill we don't go in depth in bit manipulation
# Note: Bit manipulation is very useful when we do competitive programming ,
'''
Property of XOR:

X^0 = X
X^X = X

  a ^ b ^ c ^ a ^ b     # Commutativity
= a ^ a ^ b ^ b ^ c     # Using x ^ x = 0
= 0 ^ 0 ^ c             # Using x ^ 0 = x (and commutativity)
= c
'''
# Problem 1 : Find the non-repetitive number from arr (For loops : Checkout below section )

arr = [1,2,1,2,3]
xor = 0
for i in arr:
  xor^=i
print("Non repetitive : ",xor)

# Problem 2: Swap 2 number without using helper variable

x = 3
y = 4

print("Before swap : {} and {}".format(x,y))

x ^=y
y ^=x
x ^=y

print("After swap : {} and {}".format(x,y))

# Problem 3: You are given an array A of n - 1 integers which are in the range between 1 and n.
#            All numbers appear exactly once, except one number, which is missing. Find this missing number.

x = [1,2,3,4,6,7,8,9,10]              # missing number = 5

'''
As previously, numbers are repeated , so they becomes zero because of property(x^x=0)
But now here we don't have any repeated number, so now how we do it 🤔?
'''

# Solution
'''
What we can do additionally is to also XOR all values between 1 and n:

1 ^ 2 ^ ... ^ n ^ A[0] ^ A[1] ^ ... ^ A[n - 1]
This will give us a sequence of XOR statements where elements appear as follows:

All values in the given list now appear twice:
    once from taking all the values between 1 and n
    once because they were in the original list
The missing value appears exactly once:
    once from taking all the values between 1 and n
'''
xor = 0
for i in range(1,len(x)+2):
  xor^=i

for i in x:
  xor^=i

print("Missing number : ",xor)

Non repetitive :  3
Before swap : 3 and 4
After swap : 4 and 3
Missing number :  5


**Shift Operators**

These operators are used to shift the bits of a number left or right thereby multiplying or dividing the number by two respectively. They can be used when we have to multiply or divide a number by two.

**Bitwise right shift**: Shifts the bits of the number to the right and fills 0 on voids left as a result. Similar effect as of dividing the number with some power of two.

```
Binary of 10 = 1010
Right shift by 1 bit = 0101 = 5
10 >> 1  = 0101
```

**Bitwise left shift**: Shifts the bits of the number to the left and fills 0 on voids left as a result. Similar effect as of multiplying the number with some power of two.

```
Binary of 10 = 1010
Left shift by 1 bit = 10100 = 20
10 << 1  = 10100
```


In [ ]:
# Shift operator (shift 1 bit only)

a = 10
b = -10

# print bitwise right shift operator
print("a >> 1 =", a >> 1)
print("b >> 1 =", b >> 1)

a = 5
b = -10

# print bitwise left shift operator
print("a << 1 =", a << 1)
print("b << 1 =", b << 1)

a >> 1 = 5
b >> 1 = -5
a << 1 = 10
b << 1 = -20


In [ ]:
# Shift operator (bit shifted by 2 position)

# print bitwise right shift operator
print("1 >> 2 =", 1 >> 2)
print("-1 >> 2 =", -1 >> 2)

# print bitwise left shift operator
print(" 1 << 2 =", 1 << 2)
print("-1 << 2 =", -1 << 2)

1 >> 2 = 0
-1 >> 2 = -1
 1 << 2 = 4
-1 << 2 = -4


## **range function**

The built-in function range() generates the integer numbers between
the given start integer to the stop integer, i.e., It returns a
range object. Using for loop, we can iterate over a sequence of numbers produced by the range() function.


```python
range(start, stop[, step])
```

It takes three arguments. Out of the three 2 arguments are optional. I.e., start and step are the optional arguments.

* A **`start argument`** is a starting number of the sequence. i.e., lower limit. By default, it starts with 0 if not specified.

* A **`stop argument`** is an upper limit. i.e., generate numbers up to this number, The range() doesn’t include this number in the result.

* The **`step`** is a difference between each number in the result. The default value of the step is 1 if not specified.

#### range() function Examples

Let see all the possible scenarios now. Below are the three variant of range() function.

In [ ]:
# start from 0 and end at 3 (exclude 4 as index start from 0)
list(range(4))    # step by default is 1

[0, 1, 2, 3]

In [ ]:
# Print first 5 numbers using range function
for i in range(5):
    print(i, end=', ')

0, 1, 2, 3, 4, 

In [ ]:
# start from 1 and end at 9 (exclude 10)
list(range(1,10))  # step by default is 1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# start from 2 and end at 9 (exclude 10)
list(range(2,10,1))   # step by default 1

[2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# using start, stop, and step arguments in range()
print("Printing All even numbers between 2 and 10 using range()")

for i in range(2, 10, 2):
    print(i, end=', ')

Printing All even numbers between 2 and 10 using range()
2, 4, 6, 8, 

The first is to use a negative or down step value. i.e., set the step argument of a range() to -1.

For example, if you want to display a number sequence like [5, 4, 3, 2, 1, 0] i.e., we want reverse iteration or backward iteration of for loop with range() function.

Let’s see how to loop backward using indices in Python to display a range of numbers from 5 to 0.

In [ ]:
print ("Displaying a range of numbers by reverse order")
for i in range(5, -1, -1):
    print (i, end=', ')

Displaying a range of numbers by reverse order
5, 4, 3, 2, 1, 0, 

In [ ]:
print("Printing reverse range using reversed()")
for i in reversed(range(0, 5)):
    print(i)

Printing reverse range using reversed()
4
3
2
1
0


In [ ]:
print("Checking the type")
print(type(range(0, 5)))
print(type(reversed(range(0,5))))

Checking the type
<class 'range'>
<class 'range_iterator'>


In [ ]:
# using start, stop, and step arguments in range()
print("Printing All numbers between 10 to 2 with decrement of -1 using range()")

for i in range(10, 2, -1):
    print(i, end=', ')

Printing All numbers between 10 to 2 with decrement of -1 using range()
10, 9, 8, 7, 6, 5, 4, 3, 

**Points to remember about range() function arguments**

* **range()** only works with the integers.

* All arguments must be integers. You can not use float number or any other type in a start, stop and step argument of a range().

* All three arguments can be positive or negative.

* The step value must not be zero. If a step is zero Python raises a ValueError exception

In [ ]:
# >> list(range(1,10,0))

# ValueError: range() arg 3 must not be zero

In [ ]:
# Printing inclusive range (index start from 1 and end at n)

start = 1
stop  = 5
step  = 1
stop +=step # now stop is 6

for i in range(start, stop, step):
    print(i, end=', ')

1, 2, 3, 4, 5, 

### **`Note`**

```
In for i in range() i is the iterator variable.
```
To understand what does for i in range() mean in Python, first, we need to understand the working of range() function.  The range() function uses the generator to produce numbers within a range, i.e., it doesn’t produce all numbers at once. It generates the next value only when for **loop** iteration asked for it.

In [ ]:
# Excersice (using range)
'''
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5
'''

for i in range(1,6):
  for j in range(i):
    print(i,end= ' ')
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
# In these example, we used funtion and generator
# which covered in the bottom of section

def char_range(a,b):
  for i in range(ord(a),ord(b)+1):
    yield i

val = []
for i in char_range('a','z'):
  val.append(chr(i))

print(val)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


## **Float range**

```
Python’s range() function doesn’t support the float numbers.
```
i.e.,
we cannot use floating-point or non-integer numbers in any of its arguments. we can use only integer numbers. However, we can create a custom range function where we can use float numbers like 0.1 or 1.6 in any of its arguments. I have demonstrated this in the below example.



In [ ]:
def frange(start, stop=None, step=None):

    if step==None:
        step=1.0

    if stop==None:
        stop = start
        start = 0.0

    while True:
        if (step>0 and start>=stop):
            break
        elif (step<0 and start<=stop):
            break
        yield start
        start +=step

res = frange(5.5,-5.5,-1)
print(list(res))

[5.5, 4.5, 3.5, 2.5, 1.5, 0.5, -0.5, -1.5, -2.5, -3.5, -4.5]


## 1️⃣ **Imperative programming**

### **`Note`**
```
As if now, Don't look at the code, only understand the concept, the code will be explained in below few section.
```

Imperative: Computation is performed as a direct change to program state. This style is especially useful when manipulating data structures and produces elegant yet simple code. Python fully implements this paradigm.

In imperative programming, you focus on how a program operates. Programs change state information as needed in order to achieve a goal. Here’s an example using my_list:


```python
sum = 0
for x in my_list:
    sum += x
print(sum)
```
Unlike the previous examples, the value of sum changes with each iteration of the loop. As a result, sum has state. When a variable has state, something must maintain that state, which means that the variable is tied to a specific processor. Imperative coding works on simple applications, but code executes too slowly for optimal results on complex data science applications.

## **For loop**

The for loop in Python is used to iterate over a sequence (list, tuple, string) or other iterable objects. Iterating over a sequence is called traversal.

### **Syntax of for Loop**

```python
for val in sequence:
	Body of for
```

Here, val is the variable that takes the value of the item inside the sequence on each iteration.

Loop continues until we reach the last item in the sequence.
The body of for loop is separated from the rest of the code using indentation.

In [ ]:
# for loop
for item in 'Teacher':
    print(item)

T
e
a
c
h
e
r


In [ ]:
for i in ['Hello','Good ','Morning','Ryan']:
    print(i)
print('-----------------')
for i in range(4):
    print(i)
print('-----------------')
for i in range(2,8):
    print(i)
print('-----------------')
for i in range(2,8,3):
    print(i)
print('-----------------')
for i in [5,6,7,8]:
    print(i)

Hello
Good 
Morning
Ryan
-----------------
0
1
2
3
-----------------
2
3
4
5
6
7
-----------------
2
5
-----------------
5
6
7
8


In [ ]:
# Program to find the sum of all numbers stored in a list

print('\n# ------ Without using Inbuilt sum() Function-----#\n')

# List of numbers
numbers = [6, 5, 3, 8, 4, 2, 5, 4, 11]

# variable to store the sum
total = 0

# iterate over the list
for val in numbers:
	total = total+val

print("The total is", total)


# ------ Without using Inbuilt sum() Function-----#

The total is 48


In [ ]:
# sum(iterable, start)
'''
iterable : iterable can be anything list , tuples or dictionaries, but most importantly it should be numbers.
start : this start is added to the sum of numbers in the iterable.

If start is not given in the syntax , it is assumed to be 0.
'''
print(sum(numbers))

48


In [ ]:
for i in range(4):
    for j in range(3):
        print(f'({i},{j})')

(0,0)
(0,1)
(0,2)
(1,0)
(1,1)
(1,2)
(2,0)
(2,1)
(2,2)
(3,0)
(3,1)
(3,2)


In [ ]:
#array
num = [1,2,3,4,5]
for i in num:
    print('$'*i)

$
$$
$$$
$$$$
$$$$$


In [ ]:
#Exercise!

'''
Display the image below to the right hand side where the 0 is going to be ' ',
and the 1 is going to be '*'. This will reveal an image!
'''

picture = [
  [0,0,0,1,0,0,0],
  [0,0,1,1,1,0,0],
  [0,1,1,1,1,1,0],
  [1,1,1,1,1,1,1],
  [0,0,0,1,0,0,0],
  [0,0,0,1,0,0,0]
]

# ---------- Code ----------#

for i in picture:
    for j in i:
        if j==0:
            print(' ', end='')  # when we use print() defualt end='\n' i.e next line but we want ouput to in same line so end=''
        else:
            print('*',end= '')
    print('')

print("Wow it's Tree")


   *   
  ***  
 ***** 
*******
   *   
   *   
Wow it's Tree


In [ ]:
# If loop inside print statement
width = 0
for i in range(20):
  print(i , end = ' ' if width<9 else '\n')
  width+=1
  if width==10:
    width = 0

0 1 2 3 4 5 6 7 8 9
10 11 12 13 14 15 16 17 18 19


In [ ]:
#@title Excercise :- Print each digit of a number (from first to last) { vertical-output: true, display-mode: "form" }

# This code will be hidden when the notebook is loaded.

print(
'''
Input : 12345
Output : 1 2 3 4 5
'''
)
import math

num = 12345

for i in range(int(math.log(num,10)),-1,-1):

  temp = ( num // (10**i) ) % 10
  print(temp, end = ', ')


Input : 12345
Output : 1 2 3 4 5

1, 2, 3, 4, 5, 

In [ ]:
## Print each digit of number

# Input : 12345
# Output : 1, 2, 3, 4, 5

import math

num = 12345

for i in range(int(math.log(num,10)),-1,-1):

  temp = ( num // (10**i) ) % 10
  print(temp, end = '\t')

1	2	3	4	5	

In [ ]:
# Excerise : find the two largest from the array

nums = [1,4,3,2]

first = float('-inf')

for num in nums:
    if num > first:
        second = first
        first = num
    elif num > second:
        second = num

print(first,second)

4 3


## **While loop**


The while loop in Python is used to iterate over a block of code as long as the test expression (condition) is true.

### **`NOTE`**

We generally use this loop when we don't know the number of times to iterate beforehand.

```
The while loop is somewhat similar to an if statement, it executes the code inside,
if the condition is True. However, as opposed to the if statement, the
while loop continues to execute the code repeatedly as long as the condition is True.
```
Format of while loops

```python
while condition:
  expression
```

In the while loop, test expression is checked first. The body of the loop is entered only if the test_expression evaluates to True.

After one iteration, the test expression is checked again. This process continues until the test_expression evaluates to False.


In [ ]:
'''Example to illustrate
the use of else statement
with the while loop'''

counter = 0

while counter < 3:
    print("Inside loop")
    counter = counter + 1
else:
    print("Inside else")

Inside loop
Inside loop
Inside loop
Inside else


In [ ]:
# Python interprets any non-zero value as True.
# And None and 0 are interpreted as False.

# While + else statement

error = 20

while error > 1:
  error /= 2
  print(error)
else:
  print("Loop break")

10.0
5.0
2.5
1.25
0.625
Loop break


In [ ]:
# Create a pattern using while loop

i=1
while (i<5):
    print('*'*i)
    i+=1

*
**
***
****


In [ ]:
# The following programs ask the user to enter some numbers, and then return their sum

n = int(input("Enter n : "))

sum = 0
i = 0
while i<n:
  val = int(input("Enter number : "))
  sum +=val
  i = i+1

print(sum)

Enter n : 4
Enter number : 1
Enter number : 2
Enter number : 3
Enter number : 4
10


In [ ]:
# While loop with if and else statement

# Sum the number until stops
sum = 0
while True:
  value = input("Enter value : ")
  if value =='exit' or value=='e':
    break
  else:
    sum +=int(value)
print(sum)

Enter value : 1
Enter value : 2
Enter value : 3
Enter value : 4
Enter value : 5
Enter value : exit
15


In [ ]:
#@title Excercise :- Print each digit of a number (from last to first) { vertical-output: true, display-mode: "form" }

# This code will be hidden when the notebook is loaded.

print(
'''
Input : 12345
Output : 5, 4, 3, 2, 1
'''
)
import math

num = 12345

while num:
  temp = num%10
  num//=10
  print(temp, end = ', ')
# This code will be hidden when the notebook is loaded.



Input : 12345
Output : 5, 4, 3, 2, 1

5, 4, 3, 2, 1, 

In [ ]:
## Comparing for loop and while loop

## Factorial using for loop and while loop

value = int(input("Enter value : "))
method = input("Enter methods : ")

if method=='f' or method =='for':
  #---------------- For loop ---------------------#
  fact = 1
  for i in range(1,value+1):
    fact=fact*i
  print(f'Fact of 4 is : {fact}')

else:
  #---------------- While loop ---------------------#
  facto = 1
  i = 1
  while i<=value:
    facto = facto*i
    i=i+1

  print(f'facto of 4 is : {facto}')

Enter value : 5
Enter methods : f
Fact of 4 is : 120


In [ ]:
## Compair for loop and while loop in terms of list

# Here no need to define the list
for i in ['a','b','c']:
  print(i)

print('\n')

# Here we have to define the list
arr = ['x','y','z']
i=0
while i<len(arr):
  print(arr[i])
  i=i+1

a
b
c


x
y
z


### **Reference**

- [https://www.programiz.com/python-programming/while-loop](https://www.programiz.com/python-programming/while-loop)

## **Iterables vs Iterators**


###  *`Iterables`*

```
An iterable is any Python object capable of returning its members one at a time,
permitting it to be iterated over in a for-loop. Familiar examples of iterables include lists,
tuples, and strings, set,dictionary - any such sequence can be iterated over in a for-loop.
```

###  *`Iterators`*

```
Iterator in Python is simply an object that can be iterated upon. An object which will return data, one element at
a time.
```
* An iterator is an object representing a stream of data.

* It returns the data one element at a time.

* A Python iterator must support a method called  __ next__() that takes no arguments and always returns the next element of the stream.

* If there are no more elements in the stream,
  __ next__() must raise the StopIteration exception.

* Iterators don’t have to be finite.It’s perfectly reasonable to write an iterator that produces an infinite stream of data.

###  *`Iterables vs Iterators`*

```
In Python,Iterable is anything you can loop over with a for loop.

An object is called an iterable if u can get an iterator out of it.

1. Calling iter() function on an iterable gives us an iterator.

2. Calling next() function on iterator gives us the next element.

3. If the iterator is exhausted(if it has no more elements), calling next() raises StopIteration exception.
```

<p align="center"><img src="https://miro.medium.com/max/500/1*YHHSa-AdCYxlERxRvXjZ2g.png" height="70%"/></>

## **`Reference`**

- [Analytics vidya - Medium](https://medium.com/analytics-vidhya/iterable-vs-iterator-in-python-eda1295a815e)

I Know, this defination would not help you to understand things better ... so let me give break this defination into pieces



In [ ]:
# Iterables : List, String, Tuple, Set, Dictionary

# List
arr = [1,2,3,4]
for i in arr:
  print(i,end=" -> ")

print("\n")

# String
arr = ["Hey","there","I'm", "john"]
for i in arr:
  print(i,end=" -> ")

print("\n")

# tuple
arr = (10,11,12,13)
for i in arr:
  print(i,end=" -> ")

print("\n")

# Set
arr = ("Hello", 12, 23)
for i in arr:
  print(i,end=" -> ")

print("\n")

# Dict
d  = {
        'Name':'Hritik',
        'age': 'DOB-Current',
        'Salary':'NA',
        'Fav emoji':"👨‍💻"
     }
for k,v in d.items():
  print("{} : {}".format(k,v))

1 -> 2 -> 3 -> 4 -> 

Hey -> there -> I'm -> john -> 

10 -> 11 -> 12 -> 13 -> 

Hello -> 12 -> 23 -> 

Name : Hritik
age : DOB-Current
Salary : NA
Fav emoji : 👨‍💻


In [ ]:
# so how do we know, particular datatypes is iterable or not?
# Solution :

'''
If that particular datatype contains __iter__ method , then we can say it is Iterable
Here we can see that in dir of x (i.e list) , it contain __iter__ method , so it is iterable
'''
x = [5,10,15,20,25]
print(dir(x))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
# Calling iter() function on an iterable gives us an iterator.
# So what does that means 🤔?

# Solution:
'''
So here , when we call iter function over x which is list
It generates an Iterator object of first element in x
'''
iterator = iter(x)
print(iterator)

In [ ]:
# Calling next() function on iterator gives us the next element.
'''
so when, we pass iterator object inside next function, it generates the output, which is the
first element of x.
'''
print(next(iterator))

5


In [ ]:
# So if we call next function again, it will return 2nd element of list x.
print(next(iterator))

10


In [ ]:
# So if we call next function again, it will return 3nd element of list x.
print(next(iterator))

15


In [ ]:
# Now, we call again, it will return 4th element of list x.
print(next(iterator))

20


In [ ]:
# Now, we call again, it will return 5th element of list x.
print(next(iterator))

25


In [ ]:
# So when we call again, what happen is it raise "StopIteration" exception.
'''
Because we reach end of list, and after that we don't have element in the list
'''
print(next(iterator))

StopIteration: ignored

In [ ]:
# NOTE

'''
That is how, for loop works, it calls iterables (list)
then iterables calls, iterator (which return memory location of each element in list)
Now to print the element in that perticular memory location we use "Next"
Next is like a pointer , which keep track of element which processed.
'''

# Important point :

'''
For loop internally handle "StopIteration" error, after it reaches end of list.
'''

## **4 ways to find binary to decimal**

In [ ]:
# Method 01 : Without reversing the binary number

# Input : Binary String
def bin2dec_01(binary):
    decimal = 0
    l = len(binary)
    for i in binary:
        l = l - 1
        decimal+= (2**l * int(i))
    print(decimal)

bin2dec_01('1011')

# Input : Binary array
def bin2dec_02(binary):
    decimal = 0
    l = len(binary)
    for i in binary:
        l = l - 1
        decimal+= (2**l * i)
    print(decimal)

bin2dec_02([1,0,1,1])

# Method 02: With Reversing the binary number

# Input : Binary String
def bin2dec_03(binary):
    decimal = 0
    for i,v in enumerate(list(binary)[::-1]):
        decimal += (2**i) * int(v)
    print(decimal)

bin2dec_03('1011')

# Input : Binary array
def bin2dec_04(binary):
    decimal = 0
    for i,v in enumerate(binary[::-1]):
        decimal+= (2**i) * v
    print(decimal)

bin2dec_04([1,0,1,1])

# Method 03 : Using python in-built function

# Input : Binary String
def bin2dec_05(binary):
    print(int(binary,2))

bin2dec_05('1011')

# Input : Binary array
def bin2dec_06(binary):
    res = ''
    for i in binary:
      res+=str(i)
    print(int(res,2))

bin2dec_06([1,0,1,1])

# Method 04 : Using Bit manipulation (Faster)


# Input : Binary String
def bin2dec_07(binary):
    res =  0
    for i in list(binary):
        res = (res << 1) + int(i)
    print(res)

bin2dec_07('1011')

# Input : Binary Array
def bin2dec_08(binary):
    res =  0
    for i in binary:
        res = (res << 1) + i
    print(res)

bin2dec_08([1,0,1,1])

11
11
11
11
11
11
11
11


## **2D - List**

In [ ]:
#2D-List

matrix = [[1,2,3],[4,5,6],[7,8,9]]
for i in matrix:
    print(i)

print('-----print individual item-----')
for i in matrix:
    for j in i:
        print(j)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
-----print individual item-----
1
2
3
4
5
6
7
8
9


In [ ]:
# 2-d array of booleans using list comprehension:
rows = int(input("Enter rows : "))
cols = int(input("Enter cols : "))
matrix = [[int(input("Enter value : ")) for col in range(cols)] for row in range(rows)]
print("\nMatrix : ",matrix)

Enter rows : 2
Enter cols : 2
Enter value : 1
Enter value : 2
Enter value : 3
Enter value : 4

Matrix :  [[1, 2], [3, 4]]


In [ ]:
row,col = 5,5

M = [[0 for i in range(col)] for i in range(row)]

for i in range(row):
  for j in range(row):
    M[i][j] = j

for i in range(row):
  for j in range(col):
    print(M[i][j], end = " ")
  print()

0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 


In [ ]:
#@title Excersice :- Create a column matrix  { vertical-output: true, display-mode: "both" }


# This code will be hidden when the notebook is loaded.
print(
  '''
  Input :  [1,2,5,3,1,3]
  Output :  1 1 1 1 1 1
            0 1 1 1 0 1
            0 0 1 1 0 1
            0 0 1 0 0 0
            0 0 0 0 0 0
            0 0 0 0 0 0

  Examplanation:

  Given a list A = [1,2,5,3,1,3], the function should return
  the NxN matrix, where N is size of list, every cell is colored
  with either black (0) or white (1)

  The first element of list A : 1
  so only first cell is filled with '1'

  The first element of list A : 2
  so only first cell and second cell of 2nd column is filled with '1'

  and so on.

  Note : [Source code is hidden]
  '''

)

# Sample code
def solution(A):
    n = len(A)
    M = [[0 for j in range(n)] for i in range(n)]
    for i in range(0,n,1):
        for j in range(0,n,1):
            if A[i]!=0:
                M[j][i] = 1
                A[i] = A[i]-1
            else:
                M[i][j] = 0

    for i in range(0, n,1):
        for j in range(0,n,1):
            print (M[i][j], end = " ")
        print("")

# solution(A = [1,2,5,3,1,3])


  Input :  [1,2,5,3,1,3]
  Output :  1 1 1 1 1 1 
            0 1 1 1 0 1 
            0 0 1 1 0 1 
            0 0 1 0 0 0 
            0 0 0 0 0 0 
            0 0 0 0 0 0

  Examplanation:

  Given a list A = [1,2,5,3,1,3], the function should return
  the NxN matrix, where N is size of list, every cell is colored 
  with either black (0) or white (1)

  The first element of list A : 1
  so only first cell is filled with '1' 

  The first element of list A : 2
  so only first cell and second cell of 2nd column is filled with '1' 

  and so on.

  Note : [Source code is hidden]
  


## **String - Inbuilt methods**

In [ ]:
# length of string including space
c = 'hii buddy'
print(len(c))

9


In [ ]:
# various methods for string

msg = 'Python is the most popular langauge'

# capitalize()
'''
capitalize() : method converts first character of a string to uppercase letter
and lowercases all other characters, if any.
'''

print(msg.capitalize())

# center()
'''
center() : The center() method returns a string which is padded with the specified character.

center() Parameters
  The center() method takes two arguments:

  width - length of the string with padded characters
  fillchar (optional) - padding character

The fillchar argument is optional. If it's not provided, space is taken as default argument.
'''

string = "Python is awesome"

new_string = string.center(24)

print("Centered String: ", new_string)

string = "Python is awesome"

new_string = string.center(24, '*')

print("Centered String: ", new_string)

Python is the most popular langauge
Centered String:     Python is awesome    
Centered String:  ***Python is awesome****


In [ ]:
# Count()
'''
The string count() method returns the number of occurrences of a substring in the given string.
'''

# String count() Parameters
'''
count() method only requires a single parameter for execution. However, it also has two optional parameters:

substring - string whose count is to be found.
start (Optional) - starting index within the string where search starts.
end (Optional) - ending index within the string where search ends.
'''
# define string
string = "Python is awesome, isn't it?"
substring = "is"

count = string.count(substring)

# print count
print("The count is:", count)

# Count number of occurrences of a given substring using start and end

string = "smile is awesome"
substring = "e"

# count after first 'i' and before the last 'i'
count = string.count(substring, 0, 5)

print("The count is:", count)

The count is: 2
The count is: 1


In [ ]:
# endswith()
'''
The endswith() method returns True if a string ends with the specified suffix. If not, it returns False.

The syntax of endswith() is:
    str.endswith(suffix[, start[, end]])
'''
# Parameter

'''
Return Value from endswith()
The endswith() method returns a boolean.

It returns True if strings ends with the specified suffix.
It returns False if string doesn't end with the specified suffix.
'''

text = "Python is easy to learn."

result = text.endswith('to learn')
# returns False
print(result)

result = text.endswith('to learn.')
# returns True
print(result)

result = text.endswith('Python is easy to learn.')
# returns True
print(result)

# start parameter: 7
# "programming is easy to learn." string is searched
result = text.endswith('learn.', 7)
print(result)

# Both start and end is provided
# start: 7, end: 26
# "programming is easy" string is searched

result = text.endswith('is', 7, 26)
# Returns False
print(result)

result = text.endswith('easy', 7, 26)
# returns True
print(result)

False
True
True
True
False
False


In [ ]:
# find()
'''
The find() method returns the index of first occurrence of the substring (if found). If not found, it returns -1.
'''
# Parameters for the find() method
'''
The find() method takes maximum of three parameters:

sub - It is the substring to be searched in the str string.
start and end (optional) - The range str[start:end] within which substring is searched.
'''
quote = 'Learn fundamentals of pythons'

# first occurance of 'let it'(case sensitive)
result = quote.find('of')
print("Substring 'of':", result)

# find returns -1 if substring not found
result = quote.find('small')
print("Substring 'small ':", result)

quote = 'Do small things with great love'

# Substring is searched in 'hings with great love'
print(quote.find('small things', 10))

# Substring is searched in ' small things with great love'
print(quote.find('small things', 2))

# Substring is searched in 'hings with great lov'
print(quote.find('o small ', 10, -1))

# Substring is searched in 'll things with'
print(quote.find('things ', 6, 20))


Substring 'of': 19
Substring 'small ': -1
-1
3
-1
9


In [ ]:
# index()
'''
The index() method returns the index of a substring inside the string (if found).
If the substring is not found, it raises an exception.

The syntax of the index() method for string is:
    str.index(sub[, start[, end]] )
'''

# Return Value from index()
'''
If substring exists inside the string, it returns the lowest index in the string where substring is found.
If substring doesn't exist inside the string, it raises a ValueError exception.
The index() method is similar to find() method for strings.

The only difference is that find() method returns -1 if the substring is not found,
whereas index() throws an exception.
'''
sentence = 'Python programming is fun.'

result = sentence.index('is fun')
print("Substring 'is fun':", result)

sentence = 'Python programming is fun.'

# Substring is searched in 'gramming is fun.'
print(sentence.index('ing', 10))

# Substring is searched in 'gramming is '
print(sentence.index('g is', 10, -4))

Substring 'is fun': 19
15
17


In [ ]:
# isalnum()
'''
isalnum() returns:

True : if all characters in the string are alphanumeric
False : if at least one character is not alphanumeric
'''

name = "M234onica"
print(name.isalnum())

# contains whitespace
name = "M3onica Gell22er "
print(name.isalnum())

name = "Mo3nicaGell22er"
print(name.isalnum())

name = "133"
print(name.isalnum())

True
False
True
True


In [ ]:
# isdecimal()
'''
The isdecimal() returns:

True : if all characters in the string are decimal characters.
False : if at least one character is not decimal character.
'''
s = "28212"
print(s.isdecimal())

# contains alphabets
s = "32ladk3"
print(s.isdecimal())

# contains alphabets and spaces
s = "Mo3 nicaG el l22er"
print(s.isdecimal())

True
False
False


In [ ]:
# PROTIP : If you forgot methods names like me,then try this out :)
#          This saves time, because you now won't switch to the doc to find the answer

"""
Python help() Method.
The Python help() function invokes the interactive built-in help system.
If the argument is a string, then the string is treated as the name of a module, function, class, keyword, or documentation topic, and
a help page is printed on the console.
"""
# Note: object is passed to help() (not a string)
print(help(str))


# You can try other things as well
'''
print(help(list))
print(help(dict))
print(help(print))
print(help([1, 2, 3]))
'''

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

## **List - Inbuilt methods**

### **Append method**
```
Defination : The append() method appends an element to the end of the list.
```

The syntax of the append() method is:
```
list.append(item)
```

**append() Parameters**

The method takes a single argument
```
item - an item to be added at the end of the list
The item can be numbers, strings, dictionaries, another list, and so on.
```

In [ ]:
# The append() method modifies the original list. It doesn't return any value.

# Append integer to list
number = [2,3,4,6]

number.append(9)
print('Updated number list: ', number)

# Append string to list
number = [2,3,4,6]

number.append('Hello')
print('Updated number list: ', number)

# Append list to list
number = [2,3,4,6]
number.append([1,2])
print('Updated number list: ', number)

Updated number list:  [2, 3, 4, 6, 9]
Updated number list:  [2, 3, 4, 6, 'Hello']
Updated number list:  [2, 3, 4, 6, [1, 2]]


In [ ]:
# Append 2D list to list
number = [2,3,4,6]

number.append([[1,2]])
print('Updated number list: ', number)

# Append dictionary to list
number = [2,3,4,6]

number.append({'key':2})
print('Updated number list: ', number)

# Append sets to list
number = [2,3,4,6]

number.append({6,7})
print('Updated number list: ', number)

# Append tuple to list
number = [2,3,4,6]

number.append((8,9))
print('Updated number list: ', number)

Updated number list:  [2, 3, 4, 6, [[1, 2]]]
Updated number list:  [2, 3, 4, 6, {'key': 2}]
Updated number list:  [2, 3, 4, 6, {6, 7}]
Updated number list:  [2, 3, 4, 6, (8, 9)]


### **Extend method**

```
Defination : The extend() method adds all the elements of an iterable (list, tuple, string etc.) to the end of the list.
```

The syntax of the extend() method is:
```
list.extend(iterable)
```
Here, all the elements of iterable are added to the end of list.

**extend() Parameters**
```
As mentioned, the extend() method takes an iterable such as list, tuple, string etc.
```

In [ ]:
# The extend() method modifies the original list. It doesn't return any value.

# fruits list
fruits1 = ['Apple', 'Orange']

# another list of fruits
fruits2 = ['Banana', 'Pear']

# appending fruits2 elements to fruits1
fruits1.extend(fruits2)

print('fruits List:', fruits1)

fruits List: ['Apple', 'Orange', 'Banana', 'Pear']


In [ ]:
# Add Elements of Tuple and Set to List

# languages list
languages = ['French']

# languages tuple
languages_tuple = ('Spanish', 'Portuguese')

# languages set
languages_set = {'Chinese', 'Japanese'}

# appending language_tuple elements to language
languages.extend(languages_tuple)

print('New Language List:', languages)

# appending language_set elements to language
languages.extend(languages_set)

print('Newer Languages List:', languages)

New Language List: ['French', 'Spanish', 'Portuguese']
Newer Languages List: ['French', 'Spanish', 'Portuguese', 'Japanese', 'Chinese']


### **Insert method**

```
Defination :
```

In [ ]:
# working with function

'''
# Append : The append() method appends an element to the end of the list.

The syntax of the append() method is: list.append(item)

'''
number = [2,3,4,6]
print('-----Append---------')

number.append(9)
print(number)

'''
2.insert : The list insert() method inserts an element to the list at the specified index.

'''
print('-----Insert---------')
number.insert(2,8)
print(number)

# 3.remove
print('-----Remove---------')
number.remove(8)
print(number)

# 4.pop
print('-----pop---------')
number.pop()
print(number)

# 5.clear
print('-----clear---------')
number.clear()
print(number)

-----Append---------
[2, 3, 4, 6, 9]
-----Insert---------
[2, 3, 8, 4, 6, 9]
-----Remove---------
[2, 3, 4, 6, 9]
-----pop---------
[2, 3, 4, 6]
-----clear---------
[]


In [ ]:
# index
list_item = [2,4,6,7,2,4]
print(list_item.index(6))
print(list_item.count(2))

2
2


In [ ]:
# 1.sort 2.reverse 3.sorted

item = [3,5,2,8,1]
item.sort()     # Does not return any thing
print(item)


item.reverse()
print(item)
'''
Reverse a list without using reverse method
>> item_copy = item[:]
>> print(item_copy[: : -1])
'''

print(sorted(item)) # sorted : return an list which is sorted (it creates a copy of list and sort the list)

[1, 2, 3, 5, 8]
[8, 5, 3, 2, 1]
[1, 2, 3, 5, 8]


In [ ]:
# join method works on string

sentance = ' '
new_sentance = sentance.join(['hii','i\'m', 'martin'])   # join method require an iterable i.e list
print(new_sentance)

hii i'm martin


In [ ]:
#list will update if we changing list item before calling copy function ,
# but list will not be change when u are appending and deleting after copy function
a = [2,3,4,5]
b = a.copy()
a.append(10)
print(b)

[2, 3, 4, 5]


In [ ]:
#excercise -> remove a duplicate no. from the list
numbers = [2,3,4,4,3,5]
unique = []

for i in numbers:
    if i not in unique:
        unique.append(i)

print(unique)

[2, 3, 4, 5]


## **Enumerate**

The enumerate() method adds counter to an iterable and returns it (the enumerate object).

### *`enumerate() Parameters`*

enumerate() method takes two parameters:

* iterable - a sequence, an iterator, or objects that supports iteration
* start (optional) - enumerate() starts counting from this number. If start is omitted, 0 is taken as start.

### *`Return Value from enumerate()`*

enumerate() method adds counter to an iterable and returns it. The returned object is a enumerate object.

You can convert enumerate objects to list and tuple using list() and tuple() method respectively.

### *`Reference`*

* [Programiz - Enumerate](https://www.programiz.com/python-programming/methods/built-in/enumerate)

In [ ]:
# Applying enumerate function

fruits = ['apple', 'mango', 'orange']
enumerateFruits = enumerate(fruits)
print(type(enumerateFruits))

# converting to list
print(list(enumerateFruits))

# changing the default counter
enumerateFruits = enumerate(fruits, 10)
print(list(enumerateFruits))

<class 'enumerate'>
[(0, 'apple'), (1, 'mango'), (2, 'orange')]
[(10, 'apple'), (11, 'mango'), (12, 'orange')]


In [ ]:
# Works with list
# Looping Over an Enumerate object
grocery = ['bread', 'milk', 'butter']

for item in enumerate(grocery):
  print(item)

print('\n')
for count, item in enumerate(grocery):
  print(count, item)

print('\n')
# changing default start value
for count, item in enumerate(grocery, 100):
  print(count, item)

(0, 'bread')
(1, 'milk')
(2, 'butter')


0 bread
1 milk
2 butter


100 bread
101 milk
102 butter


In [ ]:
# Work with string

for i,char in enumerate('hello'):
  print(char)

print("\n")

# work with tuple

for i,char in enumerate(('hello','i\'m','josh')):
  print(char)

h
e
l
l
o


hello
i'm
josh


## **isinstance**
```
The isinstance() function returns True if the specified object is of the specified type, otherwise False

OR

The isinstance() function checks if the object (first argument) is an instance or subclass of classinfo class (second argument).
```

### *`The syntax of isinstance() is:`*

```
isinstance(object, classinfo)
```

### *`isinstance() Parameters`*
isinstance() takes two parameters:
```
object - object to be checked
classinfo - class, type, or tuple of classes and types
```

In [ ]:
numbers = [1, 2, 3]

result = isinstance(numbers, list)
print(numbers,'instance of list?', result)

result = isinstance(numbers, dict)
print(numbers,'instance of dict?', result)

result = isinstance(numbers, (dict, list))
print(numbers,'instance of dict or list?', result)

[1, 2, 3] instance of list? True
[1, 2, 3] instance of dict? False
[1, 2, 3] instance of dict or list? True


In [ ]:
number = 5

result = isinstance(number, list)
print(number,'instance of list?', result)

result = isinstance(number, int)
print(number,'instance of int?', result)

5 instance of list? False
5 instance of int? True


In [ ]:
string = "Hello"

result = isinstance(string, int)
print(string,'instance of int?', result)

result = isinstance(string, float)
print(string,'instance of float?', result)

result = isinstance(string, str)
print(string,'instance of str?', result)

Hello instance of int? False
Hello instance of float? False
Hello instance of str? True


In [ ]:
# Will discuss about the "class" in python, later . This example is just to show you the working of isinstance.

class Foo:
  a = 5

fooInstance = Foo()

print(isinstance(fooInstance, Foo))
print(isinstance(fooInstance, (list, tuple)))
print(isinstance(fooInstance, (list, tuple, Foo)))

True
False
True


## **max and min function**

### *`Max function`*
```
max()
This function is used to compute the maximum of the values passed in its argument and lexicographically largest value
if strings are passed as arguments.

or

The Python max() function returns the largest item in an iterable. It can also be used to find the largest item between
two or more parameters.
```
### *`Min function`*
```
The Python min() function returns the smallest item in an iterable.

It can also be used to find the smallest item between two or more parameters.
```

The max() and min() function has two forms:
```
// to find the largest item in an iterable
max(iterable, *iterables, key, default)

// to find the largest item between two or more objects
max(arg1, arg2, *args, key)
```

### *`Parameters`*

- iterable - an iterable such as list, tuple, set, dictionary, etc.

- *iterables (optional) - any number of iterables; can be more than one

- key (optional) - key function where the iterables are passed and comparison is performed based on its return value.

- default (optional) - default value if the given iterable is empty

In [ ]:
# Example - 1

print("Maximum of 4,1,69,7,56 is : ",end="")
print (max(4,1,69,7,56) )

print("minimum of 4,1,69,7,56 is : ",end="")
print (min(4,1,69,7,56) )

Maximum of 4,1,69,7,56 is : 69
minimum of 4,1,69,7,56 is : 1


In [ ]:
# Example - 2
'''
One of the practical application among many are finding lexicographically largest
and smallest of Strings i.e String appearing first in dictionary or last.
'''
print("lexicographically largest : ",max("Hello", "I'm", "programmer", "who", "don't", "know", "how", "to", "use", "max", "function"))
print("lexicographically smallest : ",min("Hello", "I'm", "programmer", "who", "don't", "know", "how", "to", "use", "min", "function"))

lexicographically largest :  who
lexicographically smallest :  Hello


In [ ]:
# Example - 3
'''
Example 1: Get the largest item in a list
'''
number = [3, 2, 8, 5, 10, 6]
largest_number = max(number);
print("The largest number is:", largest_number)


'''
Example 1: Get the smallest item in a list
'''
number = [3, 2, 8, 5, 10, 6]
smallest_number = min(number);
print("The smallest number is:", smallest_number)

The largest number is: 10
The smallest number is: 2


In [ ]:
# Example 4: the largest string in a list

languages = ["Python", "C Programming", "Java", "JavaScript"]
largest_string = max(languages);
print("The largest string is:", largest_string)

# Example 5: the smallest string in a list

smallest_string = min(languages);
print("The smallest string is:", smallest_string)

The largest string is: Python
The smallest string is: C Programming


In [ ]:
# Now let's see usecase of key arguments

square = {2: 4, -3: 9, -1: 1, -2: 4}

# the largest key
key1 = max(square)
print("The largest key:", key1)    # 2

# the key whose value is the largest (lambda : In below few section you can see how lambda function works)
key2 = max(square, key = lambda k: square[k])

print("The key with the largest value:", key2)    # -3

# getting the largest value
print("The largest value:", square[key2])    # 9

The largest key: 2
The key with the largest value: -3
The largest value: 9


In [ ]:
# Now let's see usecase of key arguments

square = {2: 4, -3: 9, -1: 1, -2: 4}

# the largest key
key1 = min(square)
print("The largest key:", key1)    # 2

# the key whose value is the largest (lambda : In below few section you can see how lambda function works)
key2 = min(square, key = lambda k: square[k])

print("The key with the largest value:", key2)    # -3

# getting the largest value
print("The largest value:", square[key2])    # 9

The largest key: -3
The key with the largest value: -1
The largest value: 1


Few Notes:

- If we pass an empty iterator, a ValueError exception is raised. To avoid this, we can pass the default parameter.
- If we pass more than one iterators, the largest item from the given iterators is returned.


In [ ]:
# Same for both min() and max() function
'''
max({}) or max({}) or max('') or max(()) -> Returns ValueError
'''
# So handle this error use default argument

print(max([], default="List is empty"))
print(max((), default=[1,2,3]))
print(min({}, default=None))
print(min('', default=5))

List is empty
[1, 2, 3]
None
5


In [ ]:
# want to find max or min sum array from the given nested list
'''
Use key = sum
'''
print("max sum list : ",max([[1,2,4,3],[4,5,6],[0,9,10],[19,2,21]],key=sum))
print("min sum list : ",min([[1,2,4,3],[4,5,6],[0,9,10],[19,2,21]],key=sum))

max sum list :  [19, 2, 21]
min sum list :  [1, 2, 4, 3]


In [ ]:
# want to find max or min length array from the given nested list
'''
Use key = len
'''
print("max len list",max([[1,2,4,3],[4,5,6],[0,9,10],[19,2,21]],key=len))
print("min len list",min([[1,2,4,3],[4,5],[0,9,10],[19,2,21]],key=len))

max len list [1, 2, 4, 3]
min len list [4, 5]


In [ ]:
# want to find max or min length array from the given nested list
'''
Use key = lambda (In below few section you can see how lambda function works)
'''
print("max len list", max([[1,2,4,3],[4,5,6],[0,9,10],[19,2,21]], key = lambda i: len(i)))
print("min len list", min([[1,2,4,3],[4,5,6],[0,9,10],[19,2,21]], key = lambda i: len(i)))

max len list [1, 2, 4, 3]
min len list [4, 5, 6]


## **all**

The all() method returns True when all elements in the given iterable are true. If not, it returns False.

The syntax of all() method is:

```
all(iterable)
```


#### **`all() Parameters`** <br/>

---
all() method takes a single parameter:

  * iterable - any iterable (list, tuple, dictionary, etc.) .which contains the elements

#### **`Return Value from all()`**
----

all() method returns:

```
True - If all elements in an iterable are true
False - If any element in an iterable is false
```

#### **`Truth table for all()`**

| When    |  Return value |
|---------| ------------------  |
| All values are true  | True |
| All values are false  | False |
| One value is true (others are false)  | False |
| One value is false (others are true) | False |

In [ ]:
# Return value is boolean which is either True or False

# all values true
l = [1, 3, 4, 5]
print(all(l))                       # Result : True

# all values false
l = [0, False]
print(all(l))                       # Result : False

# one false value
l = [1, 3, 4, 0]
print(all(l))                       # Result : False

# one true value
l = [0, False, 5]
print(all(l))                       # Result : False

# empty iterable
l = []
print(all(l))          # when using all for empty iterable it return True
print(bool(l))         # without using all for empty iterable it return False (so by default [] is represent boolean 'False')

True
False
False
False
True
False


In [ ]:
## How all() works for strings

s = "This is good"
print(all(s))

# 0 is False
# '0' is True
s = '000'
print(all(s))

s = ''
print(all(s))

True
True
True


In [ ]:
# all() also works with Python dictionaries

'''
In case of dictionaries, if all keys (not values) are true or the dictionary is empty,
all() returns True. Else, it returns false for all other cases..
'''

s = {0: 'False', 1: 'False'}
print(all(s))

s = {1: 'True', 2: 'True'}
print(all(s))

s = {1: 'True', False: 0}
print(all(s))

s = {}
print(all(s))

# 0 is False
# '0' is True
s = {'0': 'True'}
print(all(s))

False
True
False
True
True


## **any**

```
The any() function returns True if any element of an iterable is True. If not, any() returns False.
```
The syntax of any() is:
```
any(iterable)
```
Parameters for the any() function
The any() function takes an iterable (list, string, dictionary etc.) in Python.

Value Returned by the any() function
The any() function returns a boolean value:

* [x] True if at least one element of an iterable is true.
* [x] False if all elements are false or if an iterable is empty

#### **`Truth table for any()`**

| When    |  Return value |
|---------| ------------------  |
| All values are true  | True |
| All values are false  | False |
| One value is true (others are false)  | True |
| One value is false (others are true) | True |
| Empty iterable | False |

**Reference**

- [Programiz - Python any](https://www.programiz.com/python-programming/methods/built-in/any)


In [ ]:
# True since 1,3 and 4 (at least one) is true
l = [1, 3, 4, 0]
print(any(l))

# False since both are False
l = [0, False]
print(any(l))

# True since 5 is true
l = [0, False, 5]
print(any(l))

# False since iterable is empty
l = []
print(any(l))

True
False
True
False


In [ ]:
'''
Using any() on Python Strings
'''
# Atleast one (in fact all) elements are True
s = "This is good"
print(any(s))

# 0 is False
# '0' is True since its a string character
s = '000'
print(any(s))

# False since empty iterable
s = ''
print(any(s))

True
True
False


In [ ]:
# 0 is False
d = {0: 'False'}
print(any(d))

# 1 is True
d = {0: 'False', 1: 'True'}
print(any(d))

# 0 and False are false
d = {0: 'False', False: 0}
print(any(d))

# iterable is empty
d = {}
print(any(d))

# 0 is False
# '0' is True
d = {'0': 'False'}
print(any(d))

False
True
False
False
True


## 2️⃣ **Functional programming**

### **`Note`**
```
As if now, Don't look at the code, only understand the concept, the code will be explained in below few section.
```

### **`Reference`** :
[Newrelic - Python Programming style](https://blog.newrelic.com/engineering/python-programming-styles/)

**Functional**: Every statement is treated as a mathematical equation and any forms of state or mutable data are avoided. The main advantage of this approach is that it lends itself well to parallel processing because there is no state to consider. Many developers prefer this coding style for recursion and for lambda calculus. (Note that Python’s implementation of functional programming deviates from the standard—read, is impure— because it’s possible to maintain state and create side effects if you’re not careful.

## *`Using the functional coding style`*

The functional coding style treats everything like a math equation. The two most common ways to compute the sum of my_list would be to use a local function or a lambda expression. Here’s how you’d do it with a local function in Python 3.6:

```python
import functools
my_list = [1, 2, 3, 4, 5]
def add_it(x, y):
    return (x + y)
sum = functools.reduce(add_it, my_list)
print(sum)  # Output : 15

```

The functools package provides access to higher-order functions for data manipulation. However, you don’t always use it to perform functional programming with Python. Here’s a simple example using my_list with a lambda function:

```python
square = lambda x: x**2
double = lambda x: x + x
print(list(map(square, my_list)))      # Output : [1, 4, 9, 16, 25]
print(list(map(double, my_list)))      # Output : [2, 4, 6, 8, 10]
```

As you can see, the lambda expression is simpler (or, at least, shorter) than a similar procedural approach. Here’s a lambda function version of the functools.reduce() call:
```python
import functools
my_list = [1, 2, 3, 4, 5]
sum = functools.reduce(lambda x, y: x + y, my_list)
print(sum)      # Output : 15
```

## **Map**

In [ ]:
def times(var):
    return var*2;
    load

In [ ]:
times(2)

4

In [ ]:
seq = [1,2,3]

list(map(times,seq))

[2, 4, 6]

## **Lambda**

In [ ]:
# instead of writing like this we can write
# def times(var):
#     return var*2;

t = lambda var : var*2

In [ ]:
t(3)

6

In [ ]:
list(map(t,seq))

[2, 4, 6]

## **Filter**

In [ ]:
list(map(lambda num : num %2 ==0,seq))

[False, True, False]

In [ ]:
list(filter(lambda num : num %2 ==0,seq))

[2]

## **Unpacking**

In [ ]:
#unpacking
coordinates = [2,3,4]
# x = coordinates[0]
# y = coordinates[1]
# z = coordinates[2]
# instead of writing like this we can write
x,y,z = coordinates  #unpacking -> work with both list and tuple
print(x)

larger_cordinates = [1,2,3,4,5,6,7,8]     # a,b,c contain values 1,2,3 but rest will be stored in others variable using (*)
a,b,c,*other = larger_cordinates
print(other)

a,b,c,*other,d = larger_cordinates
print(other,d)

box_cordinates = [50,100,200,200]
(x,y,w,h) = box_cordinates
print(x,y,w,h)



2
[4, 5, 6, 7, 8]
[4, 5, 6, 7] 8
50 100 200 200


## **Zip**

In [ ]:
# Exercise
def wordListToFreqDict(wordstring):

  wordlist = wordstring.split()
  wordfreq = [wordlist.count(p) for p in wordlist]
  return dict(list(zip(wordlist,wordfreq)))

wordstring ='it was the best of times it was the worst of times , it was the age of wisdom it was the age of foolishness'
print(wordListToFreqDict(wordstring))

{'it': 4, 'was': 4, 'the': 4, 'best': 1, 'of': 4, 'times': 2, 'worst': 1, ',': 1, 'age': 2, 'wisdom': 1, 'foolishness': 1}


## **Itertools**
---
[Python’s Itertool](https://www.geeksforgeeks.org/python-itertools/) is a module that provides various functions that work on iterators to produce complex iterators. This module works as a fast, memory-efficient tool that is used either by themselves or in combination to form iterator algebra.

Iterators in Python is an object that can iterate like sequence data types such as list, tuple, str and so on.

### **Itertools – zip_longest()**


- This iterator falls under the category of Terminating Iterators.

- It prints the values of iterables alternatively in sequence. If one of the iterables is printed fully, the remaining values are filled by the values assigned to fillvalue parameter.

In [ ]:
# zip_longest( iterable1, iterable2, fillval)
# Similar to zip function but it also works for iterators of different length

import itertools

# using zip_longest() to combine two iterables.
print("The combined values of iterables is  : ")
print(*(itertools.zip_longest('ABCD', 'EFGHI', fillvalue ='_' )))

The combined values of iterables is  : 
('A', 'E') ('B', 'F') ('C', 'G') ('D', 'H') ('_', 'I')


In [ ]:
#@title Excercise : Merge Strings Alternately { vertical-output: true, display-mode: "both" }

print(
'''
Input: word1 = "abc", word2 = "pqr"
Output: "apbqcr"
Explanation: The merged string will be merged as so:
word1:  a   b   c
word2:    p   q   r
merged: a p b q c r

NOTE : [Source code is hidden]
'''
)
# This code will be hidden when the notebook is loaded.





Input: word1 = "abc", word2 = "pqr"
Output: "apbqcr"
Explanation: The merged string will be merged as so:
word1:  a   b   c
word2:    p   q   r
merged: a p b q c r

NOTE : [Source code is hidden]



## **Ways Convert 2D list to 1D list**

Given a 2D list, write a Python program to convert the given list into a flattened list.



In [ ]:
# Method 1: Using chain.iterable()

from itertools import chain

grid = [[1, 2, 3],
            [3, 6, 7],
            [7, 5, 4]]

# printing initial list
print ("initial list ", grid)

# converting 2d list into 1d
# using chain.from_iterables
flatten_list = list(chain.from_iterable(grid))

# printing flatten_list
print ("final_result", flatten_list)

initial list  [[1, 2, 3], [3, 6, 7], [7, 5, 4]]
final_result [1, 2, 3, 3, 6, 7, 7, 5, 4]


In [ ]:
# Method 02: Using list comprehension

# using list comprehension
flatten_list = [j for sub in grid for j in sub]

# printing flatten_list
print ("final_result", flatten_list)

final_result [1, 2, 3, 3, 6, 7, 7, 5, 4]


In [ ]:
# Method 03: Using functools.reduce

from functools import reduce

flatten_list = reduce(lambda z, y :z + y, grid)

# printing flatten_list
print ("final_result", flatten_list)

final_result [1, 2, 3, 3, 6, 7, 7, 5, 4]


To make it slightly faster you could can use operator.add, which is built-in, instead of lambda:


In [ ]:
from operator import add

flatten_list = reduce(add, grid)

# printing flatten_list
print ("final_result", flatten_list)

final_result [1, 2, 3, 3, 6, 7, 7, 5, 4]


In [ ]:
# Method #4: Using sum
'''
sum has an optional argument: sum(iterable [, start])
NOTE: sum (its fast for short list but not for long list)
'''

flatten_list = sum(grid, [])

print("final_result", flatten_list)

final_result [1, 2, 3, 3, 6, 7, 7, 5, 4]


this works because the + operator happens to be the concatenation operator for lists, and you've told it that the starting value is [ ] - an empty list.

but the documentaion for sum advises that you use itertools.chain instead, as it's much clearer.

## 3️⃣ **Procedural Programming**


### **`Note`**
```
As if now, Don't look at the code, only understand the concept, the code will be explained in below few section.
```

Tasks are treated as step-by-step iterations where common tasks are placed in functions that are called as needed. This coding style favors iteration, sequencing, selection, and modularization. Python excels in implementing this particular paradigm.


## *`Using the procedural coding style`*

The procedural style relies on procedure calls to create modularized code. This approach simplifies your application code by breaking it into small pieces that a developer can view easily. Even though procedural coding is an older form of application development, it’s still a viable approach for tasks that lend themselves to step-by-step execution. Here’s an example of the procedural coding style using my_list:
```python
def do_add(any_list):
    sum = 0
    for x in any_list:
        sum += x
    return sum
print(do_add(my_list))
```
The use of a function, do_add(), simplifies the overall code in this case. The execution is still systematic, but the code is easier to understand because it’s broken into chunks. However, this code suffers from the same issues as the imperative paradigm in that the use of state limits execution options, which means that this approach may not use hardware efficiently when tackling complex problems.

## **Python Identifiers**

An identifier is a name given to entities like class, functions, variables, etc. It helps to differentiate one entity from another.

## **Function**

In Python, a function is a group of related statements that performs a specific task.

Functions help break our program into smaller and modular chunks. As our program grows larger and larger, functions make it more organized and manageable.

Furthermore, it avoids repetition and makes the code reusable.

#### **`Syntax of Function`**

```python
def function_name(parameters):
	"""docstring"""
	statement(s)
  return
```

* Keyword def that marks the start of the function header.
* Optional documentation string (docstring) to describe what the function does.
* One or more valid python statements that make up the function body. Statements must have the same indentation level (usually 4 spaces).
* An optional return statement to return a value from the function.


#### **Reference** :

* [Programiz - Python Function](https://www.programiz.com/python-programming/function)

In [ ]:
# Function without arguments
def text():
    print("i'm John")

print("hii")
text()

hii
i'm John


In [ ]:
# Function without arguments
def greet(name):
    """
    This function greets to
    the person passed in as
    a parameter
    """
    print("Hello, " + name + ". Good morning!")

greet('Paul')

Hello, Paul. Good morning!


In [ ]:
# In Python, we can set default values for arguments.
# If the function is called without the argument, the default value is used.

'''
Type of arguments clearly explained in few section below
'''

def calculate (num1, num2=4):
  res = num1 * num2
  print(res)

calculate(5, 6)

30


In [ ]:
'''
 Return: If we doesn't return anything then function will return 'none' by default
 Note : As soon we return something from the function it will exit from that function
 i.e if we write any peice of code after return statement , it would not execute
'''

# Note -> if you don't write return statement then it will return object which is : none

def cube(n):
    print(n**3)                     # output : 27
print(cube(3))                      # output : None

def square(num):
    return num*num
result = square(5)
print(result)                       # output : 25

27
None
25


In [ ]:
# Nested function
# Sum function calling the multiply function

def sum_function(num1,num2):
    def multiply_function(n1,n2):
        return n1*n2

    return multiply_function(num1,num2)

total = sum_function(5,2)
print(total)

10


In [ ]:
# Adding multiple return statements doesn’t perform any task.
# Once function execution encountered with the return statement,
# it stops the function execution by returning whatever specified by the return statement

def outerFun(a, b):
    def innerFun(c, d):
        return c + d
    return innerFun(a, b)
    return a

result = outerFun(5, 10)
print(result)

15


In [ ]:
'''
def fun1(num):
    return num + 25

fun1(5)
print(num)
'''

# We must accept the return value of a function into a variable.
# so we can access it in outside function like this

In [ ]:
def add(a, b):
    return a+5, b+5

result = add(3, 2)
print(result)
print(type(result))

# Destructure

m,n =  result
print('m = ', m ,'and','n = ', n)

(8, 7)
<class 'tuple'>
m =  8 and n =  7


In [ ]:
# -------------- Exercise ---------- #

'''
input : ['a','v','a','x','b','x','d','g']
output : ['a', 'b', 'd', 'g', 'v', 'x']
'''

# Remove duplicates
# print duplicate value
# print list without duplicate
# sort without inbuilt function


# ------------ Remove duplicate --------------- #
input_list = ['a','v','a','x','b','x','d','g']

unique = []
duplicate = []

for i in input_list:
    if i not in unique:
        unique.append(i)
    else:
        duplicate.append(i)

print(f'unique list : {list(unique)}')
print(f'duplicate element : {list(duplicate)}')

# ----------- Sort with using inbuilt function ------------- #

d = list(sorted(unique))

print(f'sorted list : {d}')

unique list : ['a', 'v', 'x', 'b', 'd', 'g']
duplicate element : ['a', 'x']
sorted list : ['a', 'b', 'd', 'g', 'v', 'x']


In [ ]:

# ----------- Sort without using inbuilt function ------------- #

'''
used lot of function because to understand what is use case of each function.
'''

# char to ascii
number_list = list(map(lambda x:ord(x),unique))
print(f'char to ascii : {number_list}')

# sort list of ascii value
new_list = []
def sorting(number_list):
    while number_list:
        min = number_list[0]
        for x in number_list:
            if x<min:
                min=x
        new_list.append(min)
        number_list.remove(min)

sorting(number_list)
print(f'sorted ascii list : {list(new_list)}')

# convert ascii list to char list
final_list =[]

for i,val in enumerate(new_list):
    final_list.insert(i,chr(val))   # we can also use append here (just to show you the usecase)

print(f'ascii to char list : {list(final_list)}')

char to ascii : [97, 118, 120, 98, 100, 103]
sorted ascii list : [97, 98, 100, 103, 118, 120]
ascii to char list : ['a', 'b', 'd', 'g', 'v', 'x']


## **Docstring**
```
The first string after the function header is called the docstring and is short for documentation string.
It is briefly used to explain what a function does.

Although optional, documentation is a good programming practice.
```

Inbuilt function in python already includes docstring ,so when you hover over any function ,you can see what each function do.

In [ ]:
# Docstring
'''
         # this is known as Docstring
'''

# Usecase of docstring
def mean_function(n1,n2):
    '''
    Info : this function is used to find the mean
    '''
    return (n1+n2)/2


help(mean_function)

print("#--------------------------------------------------------------------#")
# or else we can use

print(mean_function.__doc__)

Help on function mean_function in module __main__:

mean_function(n1, n2)
    Info : this function is used to find the mean

#--------------------------------------------------------------------#

    Info : this function is used to find the mean 
    


## **Scope and Lifetime of variables**

Scope of a variable is the portion of a program where the variable is recognized. Parameters and variables defined inside a function are not visible from outside the function. Hence, they have a local scope.

The lifetime of a variable is the period throughout which the variable exits in the memory. The lifetime of variables inside a function is as long as the function executes.

They are destroyed once we return from the function. Hence, a function does not remember the value of a variable from its previous calls.

Here is an example to illustrate the scope of a variable inside a function.

In [ ]:
def my_func():
	x = 10
	print("Value inside function:",x)

x = 20
my_func()
print("Value outside function:",x)

Value inside function: 10
Value outside function: 20


## **Scope rules**


In [ ]:
# Scope rules
'''
1. Start with local function scope ( if variable present inside the function just return it - As shown in eg 1 )
2. Check variable present in parent scope ( As shown in eg 2. )
3. Check variable present in global scope
4. Built-in python function ( As shown in eg 3)
'''

# -------------------Example 1------------------------- #

# Global variable
a = 5

def confusion():
    a = 1
    return a

print(confusion())        # Answer = 1
print(a)                  # Answer = 5


1
5


In [ ]:
# ------------------- Example 2 ------------------------- #

a = 5
def parent():
    a = 1
    def confusion():
        return a
    return confusion()

print(parent())           # Answer = 1
print(a)                  # Answer = 5

1
5


In [ ]:
# ------------------- Example 3 ------------------------- #


def parent():
    def confusion():
        return sum
    return confusion()

print(parent())           # Answer = <built-in function sum>  ( sum in inbuilt function in python )
print(a)                  # Answer = 5

<built-in function sum>
5


In [ ]:
# -------------------Example 4 ------------------------- #


# if python keyword (like sum, len, max, min) used as variable then it will act like a normal variable not a function
sum = 0
def parent():
    def confusion():
        return sum
    return confusion()

print(parent())           # Answer = 0
print(a)                  # Answer = 5

0
5


## **Parameter and Arguments**

In [ ]:
# ------------------------ Parameter and arguments ---------------------------- #

# Parameter -> is placeholder that we passed to the function

def text(f_name, l_name):
    print(f'Good morning, {f_name} {l_name}')
print("Hello")

text('Hritik','jaiswal')              # Argument -> is actual value that you gone pass inside function

Hello
Good morning, Hritik jaiswal


In [ ]:
# ------------------------ Type of arguments ---------------------------- #

def say_hello(firstName, lastName):
    print(f'Hello {firstName}  {lastName}')

# Positional arguments : Require to maintain the position of arguments
say_hello('Hritik','Jaiswal')

# Keyword arguments : we change the order of passed arguments
'''
keyword argument -> its helpful when you don't want to pass argument in order you can pass in any order
'''
def text(discount , shipping ,total ):
    print(f'Here total is {total} including shipping charges {shipping} + discount {discount}')

text(shipping=2000,total=5000,discount=500)

# Default arguments : Even if you haven't passed , any argument to a function , the default parameters will be considered as arguments

def greeting(name='Hritik',greet='Morning'):
    print(f'Good {greet}, {name}')

greeting()
greeting('mike')
greeting(greet='night')


Hello Hritik  Jaiswal
Here total is 5000 including shipping charges 2000 + discount 500
Good Morning, Hritik
Good Morning, mike
Good night, Hritik


In [ ]:
def fun1(name, age):
    print(name, age)

fun1(name='Emma', age=23)   # keyword arguments
fun1('Emma', 23)            # Positional arguments

# fun1(name='Emma', 23)

Emma 23
Emma 23


```
Explanation:

We can pass either use either positional arguments or keyword arguments, not both at the same time.

If you try to do do you will get syntax Error The positional argument follows keyword argument

Positional arguments: fun1('Emma', 23)
keyword arguments: fun1(name='Emma', age=23)
```

## **Method and Function in Python**

**Java** is also an OOP language, but their is no concept of Function in it. But **Python** has both concept of Method and Function.


### **`Method`**

* Method is called by its name, but it is associated to an object i.e it's dependent on class.

  ```python
  # Basic Python method
  class class_name
      def method_name () :
          ......
          # method body
          ......
  ```
* A method is implicitly passed the object on which it is invoked.
* It may or may not return any data.
```python
# Python 3  User-Defined  Method
class ABC :
    def method_abc (self):
        print("I am in method_abc of ABC class. ")

  class_ref = ABC() # object of ABC class
  class_ref.method_abc()
```

* A method can operate on the data (string, list, tuple, dictionary, sets).
  #### **` Inbuilt Methods :`**
  ```python
  >> 'hellooooo'.upper()        # upper() is method : prints HELLOOOOO
  >> x = [1,2,3,2].count(2)     # index() is method : prints 2
  >> (1,2,3,2).index(2)         # index() is method : prints 1
  ```

### **`Function`**

* Function is block of code that is also called by its name. (independent).

  ```python
  def function_name ( arg1, arg2, ...) :
    ......
    # function body
    ......
  ```


* The function can have different parameters or may not have any at all. If any data (parameters) are passed, they are passed explicitly.

* It may or may not return any data.
  ```python
    def Subtract (a, b):
        return (a-b)

    print( Subtract(10, 12) ) # prints -2
  ```
* Function does not deal with Class and its instance concept.

   #### **` Inbuilt Function :`**
   ```python
    print(sum([5, 15, 2]))             # sum() is function : prints 22
    print(len([5, 15, 2]))             # len() is function : prints 3
    print(max(1,4,7,3))                # max() is function : prints 7
   ```

### **Reference**

* [GeeksForGeeks - Method vs Function](https://www.geeksforgeeks.org/difference-method-function-python/)


## **args(arguments) and kwargs(keyword arguments)**

```python
def super_function(args):
    return sum(args)

print(super_function(1,2,3,4))

if we run above code then we get following error i.e
TypeError: super_function() takes 1 positional argument but 4 were given
```

To accept multiple values or if the number of arguments is unknown, we can add * before the parameter name to accept arbitrary arguments. i.e., To accept Variable Length of Positional Arguments, i.e., To create functions that take n number of Positional arguments we use *args(prefix a parameter name with an asterisk * ).

To suppress the error , we will use (*)
```python
def super_function(*args):
    print(args)
    return sum(args)    # sum of tuple

print(super_function(1,2,3,4))             ## prints : 10
```

we have also keywords arguments , that will be are 2nd arguments

```python
def super_function(*args,**kwargs):
    print(args)
    print(kwargs)
    total=0
    for i in kwargs.values():
        total+=i

    return sum(args)+total    # sum of tuple + total

print(super_function(1,2,3,4, num1=10,num2=20))
```

```
if we are using the *args and **kwargs as parameter then we
have to follow one rule i.e

parameters follow order : (params, *args, default params,**kwargs)
```

Example

```python

def display(**kwargs):
    for i in kwargs:
        print(i)
display(emp="Kelly", salary=9000)
```
output
```
emp
salary
```
To accept Variable Length of Keyword Arguments, i.e., To create functions that take n number of Keyword arguments we use **kwargs(prefix a parameter name with a double asterisk ** ).

keyword arguments: display(emp="Kelly", salary=9000)

This **kwargs collects all passed arguments into a new dictionary, where the argument names are the keys =>
**kwargs.keys(), and their values are the key’s value => **kwargs.value().

So to get the values we need to iterate the kwargs dictionary like this
```
('emp', 'Kelly')
('salary', 9000)
```

## **Quizzzz time** 🎉

In [ ]:
#@title Give me a name { display-mode: "code" }

# This code will be hidden when the notebook is loaded.
x = 2
print(x)


NameError: ignored


## **Exception**

In [ ]:
#exception -> when we try to input string value instead of int
# age = int(input("your age"))
# print(age)

try:
    age = int(input("your age : "))
    print(age)
except ValueError:
    print('invalid value')

your age : twenty
invalid value


In [ ]:

try:
    age = int(input("your age : "))
    income = 20000
    risk = float(income/age);
    print(f'risk is {risk}')
except ValueError and ZeroDivisionError:
    print("invalid value or age can't be negative ")

your age : 0
invalid value or age can't be negative 


## 4️⃣ **Object-oriented programming**

### **`Note`**
```
As if now, Don't look at the code, only understand the concept, the code will be explained in below few section.
```

The object-oriented programming paradigm considers basic entities as objects whose instance can contain both data and the corresponding methods to modify that data. The different principles of object-oriented design help code reusability, data hiding, etc., but it is a complex beast, and writing the same logic an in object-oriented method is tricky.


Object-oriented coding is all about increasing an application’s ability to reuse code and make it easier to understand. The encapsulation that object-orientation provides allows developers to treat code as a black box. Using object-orientation features like inheritance make it easier to expand the functionality of existing code. Here is the my_list example in object-oriented form:

```python

class ChangeList(object):
    def __init__(self, any_list):
        self.any_list = any_list
    def do_add(self):
      self.sum = sum(self.any_list)
create_sum = ChangeList([1,2,3,4,5])
create_sum.do_add()
print(create_sum.sum)     # Output : 15

```
In this case, create_sum is an instance of ChangeList. The inner workings of ChangeList don’t matter to the person using it. All that really matters is that you can create an instance using a list and then call the do_add() method to output the sum of the list elements. Because the inner workings are hidden, the overall application is easier to understand.

### **`Reference`** :
[Newrelic - Python Programming style](https://blog.newrelic.com/engineering/python-programming-styles/)


## **Class**

An **`object`** is simply a collection of data (variables) and methods (functions) that act on those data.

Similarly, a **`class`** is a blueprint for that object.


#### **NOTE** :
```
Every function in the class contain self as a parameter.
```

In [ ]:
#class
# 1) type -1

class rect:
    def rect_area(self):
        print("area")
p = rect()
p.rect_area()



area


In [ ]:
# 2) type -2
class Employee:
    def __init__(self, first, last , salary):
        self.first = first
        self.last = last
        self.salary = salary
        self.email = first + '.'+last +'@gmail.com'

    def fullname(self):
        return "{} {}".format(self.first,self.last)

emp1 = Employee('Hritik','Jaiswal',5000)
emp2 = Employee('Aniket','Jaiswal',6000)

#their are two methods
print(emp1.fullname())
print(Employee.fullname(emp1))


Hritik Jaiswal
Hritik Jaiswal


In [ ]:
# 3) type -3
class Point:
    def __init__(self,a,l,h):
        self.a = a
        self.l = l
        self.h = h

    def square(self):
        print(f"area of square :{self.a*self.a}")

    def rectangle(self):
        print("area of rectangle is : {}".format(self.l*self.h))


#create a object
point1 = Point(3,2,3)
point1.square()
point1.rectangle()

area of square :9
area of rectangle is : 6


## **Class attributre vs Instance attribute**

### *`Python Class Variable vs. Instance Variable: What’s the Difference?`*

A Python class attribute is an attribute of the class (circular, I know), rather than an attribute of an instance of a class.

Let’s use a Python class example to illustrate the difference. Here, *`class_var`* is a class attribute, and *`i_var`* is an instance attribute:

```python
class MyClass(object):
    # Class attribute
    class_var = 1

    def __init__(self, i_var):
        # Instance (object) attribute
        self.i_var = i_var
```

Note that all instances of the class have access to *`class_var`*, and that it can also be accessed as a property of the class itself:

In [ ]:
class MyClass(object):
    # Class attribute
    class_var = 1

    def __init__(self, i_var):
        # Instance (object) attribute
        self.i_var = i_var

foo = MyClass(2)
bar = MyClass(3)

print("foo.class_var : ",foo.class_var, "foo.i_var : ",foo.i_var)
print("bar.class_var : ",bar.class_var, "bar.i_var : " ,bar.i_var)

foo.class_var :  1 foo.i_var :  2
bar.class_var :  1 bar.i_var :  3


### *`Class vs. Instance Namespaces`*

To understand what’s happening here, let’s talk briefly about Python namespaces.


A *`namespace`* is a system to have a unique name for each and every object in Python. An object might be a variable or a method. Python itself maintains a namespace in the form of a Python dictionary.

Let’s go through an example, a directory-file system structure in computers. Needless to say, that one can have multiple directories having a file with the same name inside of every directory. But one can get directed to the file, one wishes, just by specifying the absolute path to the file.

Real-time example, the role of a namespace is like a surname. One might not find a single “Alice” in the class there might be multiple “Alice” but when you particularly ask for “Alice Lee” or “Alice Clark” (with a surname), there will be only one (time being don’t think of both first name and surname are same for multiple students).

On the similar lines, Python interpreter understands what exact method or variable one is trying to point to in the code, depending upon the namespace. So, the division of the word itself gives little more information. Its Name (which means name, an unique identifier) + Space(which talks something related to scope). Here, a name might be of any Python method or variable and space depends upon the location from where is trying to access a variable or a method.

<p align="center"><img src="https://media.geeksforgeeks.org/wp-content/uploads/types_namespace-1.png" width="40%"/></p>

```
Lifetime of a namespace :

A lifetime of a namespace depends upon the scope of objects, if the scope of an object ends,

the lifetime of that namespace comes to an end.
Hence, it is not possible to access inner namespace’s objects from an outer namespace.
```

Example:

```python
# var1 is in the global namespace
var1 = 5
def some_func():

    # var2 is in the local namespace
    var2 = 6
    def some_inner_func():

        # var3 is in the nested local
        # namespace
        var3 = 7
```
Depending on the context, you may need to access a namespace using dot syntax (e.g., *`object.name_from_objects_namespace`*) or as a local variable (e.g., *`object_from_namespace`*). As a concrete example:
```python
class MyClass(object):
    ## No need for dot syntax
    class_var = 1

    def __init__(self, i_var):
        self.i_var = i_var

## Need dot syntax as we've left scope of class namespace
MyClass.class_var
## 1
```

Python classes and instances of classes each have their own distinct namespaces represented by pre-defined attributes *`MyClass. __ dict__`* and *`instance_of_MyClass. __ dict__`*, respectively.

When you try to access an attribute from an instance of a class, it first looks at its instance namespace.
- If it finds the attribute, it returns the associated value.
- If not, it then looks in the class namespace and returns the attribute (if it’s present, throwing an error otherwise).

For example:
```python
foo = MyClass(2)

## Finds i_var in foo's instance namespace
foo.i_var
## 2

## Doesn't find class_var in instance namespace…
## So look's in class namespace (MyClass.__dict__)
foo.class_var
## 1
```

The instance namespace takes supremacy over the class namespace: if there is an attribute with the same name in both, the instance namespace will be checked first and its value returned. Here’s a simplified version of the code (source) for attribute lookup:

```python
def instlookup(inst, name):
    ## simplified algorithm...
    if inst.__dict__.has_key(name):
        return inst.__dict__[name]
    else:
        return inst.__class__.__dict__[name]
```
And, in visual form:

<p align="center"><img src="https://uploads.toptal.io/blog/image/301/toptal-blog-image-1392824596580.png" /></p>


### **Reference**

- [TopTal - Python class attributes](https://www.toptal.com/python/python-class-attributes-an-overly-thorough-guide)

- [GeeksForGeeks - Namespace and scope in python](https://www.geeksforgeeks.org/namespaces-and-scope-in-python/)

## **Inheritance**

In [ ]:
#inheritance -> dog and cat are inherite a class mammel
class mammel:
    def walk(self):
        print("walk")

class dog(mammel):
    def bark(self):
        print("bark")

class cat(mammel):
    pass

dog1 = dog()
dog1.bark()

cat1 = cat()
cat1.walk()

bark
walk


## **Multiprocessing**

### **NOTE**

If you guys running the code on PYTHON IDLE it Won't work ->
[See here for more info](https://stackoverflow.com/questions/21198857/python-multiprocessing-example-not-working)

**Why exactly is the commend "if _name_ == '__main__':"  required?**

**Answer** :
```
Since you're importing the multiprocessing module, you use "if _name_ == '__main__':"
to avoid unintended side effects, such as starting a new process.
A module that doesn't have it, when imported, runs as if it were being ran directly.
By including the "if" statement there, this will only allow the code within that "if" statement to run if ran directly (such as running it yourself),
whereas if you were to import a module that has that "if" statement,
it "loads" it in a sense, since it's no longer referred to as "__main__".

If you ran it directly, it's "labelled" as "__main__".
When imported, it's "labelled" as it's filename, more or less.
```

In [ ]:
import multiprocessing
import time

# Example - 01

start = time.perf_counter()

def do_something():
    print('Sleeping for 1 second')
    time.sleep(1)
    print('Done sleeping...')

if __name__ == '__main__':
    p1 = multiprocessing.Process(target=do_something) # Just initializing it, not calling it ( Don't do this do_something())

    # To start the process
    p1.start()

    finish = time.perf_counter()
    print(f'Finished in {round(finish-start,4)} seconds')

# As it executing do_something function, it sees that cpu will be idle for 1 sec
# So it jump to finish statement and printed the finished time
# And after 1 sec, It doesn't resume where it was stoped (it not executed the "Done sleeping .." statement)

Finished in 0.0056 seconds
Sleeping for 1 second


In [ ]:
start = time.perf_counter()

def do_something():
    print('Sleeping for 1 second')
    time.sleep(1)
    print('Done sleeping...')

if __name__ == '__main__':
    p1 = multiprocessing.Process(target=do_something) # Just initializing it, not calling it ( Don't do this do_something())

    # To start the process
    p1.start()
    # Use join : To fully execute the function
    p1.join()
    finish = time.perf_counter()
    print(f'Finished in {round(finish-start,4)} seconds')

Sleeping for 1 second
Done sleeping...
Finished in 1.0287 seconds


In [ ]:
# Example 03 : Two processes
start = time.perf_counter()

def do_something():
    print('Sleeping for 1 second')
    time.sleep(1)
    print('Done sleeping...')

if __name__ == '__main__':
    p1 = multiprocessing.Process(target=do_something) # Just initializing it, not calling it ( Don't do this do_something())
    p2 = multiprocessing.Process(target=do_something)

    # To start the process
    p1.start()
    p2.start()
    p1.join()
    p2.join()

    finish = time.perf_counter()
    print(f'Finished in {round(finish-start,4)} seconds')

Sleeping for 1 second
Sleeping for 1 second
Done sleeping...
Done sleeping...
Finished in 1.035 seconds


In [ ]:
# Example : Running 10 Processes for 1 sec, so instead of taking 10 sec to execute the code, it will take only 1 sec
start = time.perf_counter()

def do_something():
    print('Sleeping for 1 second')
    time.sleep(1)
    print('Done sleeping...')

if __name__ == '__main__':

  processes = []

  # We creating a 10 processes here
  for _ in range(10):
    p = multiprocessing.Process(target=do_something)
    p.start()
    processes.append(p)

  for process in processes:
    process.join()

  finish = time.perf_counter()
  print(f'Finished in {round(finish-start,4)} seconds')

Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Sleeping for 1 second
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Finished in 1.1446 seconds


In [ ]:
# Example : Running 10 Processes for 1.5 sec so instead of taking 10 sec to execute the code, it will take only 1 sec
start = time.perf_counter()

def do_something(seconds):
    print(f'Sleeping for {seconds} second')
    time.sleep(1)
    print('Done sleeping...')

if __name__ == '__main__':

  processes = []

  # We creating a 10 processes here
  for _ in range(10):
    p = multiprocessing.Process(target=do_something,args=[1.5])
    p.start()
    processes.append(p)

  for process in processes:
    process.join()

  finish = time.perf_counter()
  print(f'Finished in {round(finish-start,4)} seconds')

Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Sleeping for 1.5 second
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Done sleeping...
Finished in 1.1307 seconds


## **Module**



In [ ]:
#module -> module.ipynb file which we have created we can directly import function also
#we need to install from anaconda prompt -> pip install import-ipynb
import import_ipynb

import module
from module import cm2m

cm2m(100)
m2cm

1.0


In [ ]:
numbers = [5,4,6,8,10]
print(max(numbers))
print(min(numbers))


10
4


## **Packages**


package -: we can create a seperate .py file and extract this file and import into another file as similar to module

package is collections of different modules

### Type of Module

        1) Absolute module
from mypackage.mymodule1 import class A
obj = class A

        2) relative module
if im working in "module1" & i want to import Class C from "module2" into my "module1"

```python
from module2 import classC
obj = classC()
```




## **Random**


In [ ]:
import random

for i in range(3):
    print(random.random())

0.8556515733440572
0.9018671283206765
0.6655666651378818


In [ ]:
for i in range(3):
    print(random.randint(10,20))

12
20
15


In [ ]:
# randomly choose the value
members = ['hritik', 'jaiswal','aniket','shweta']
show = random.choice(members)
print(show)

jaiswal


In [ ]:
#excercise -> dice thrown give random value

class Dice:
    def roll(self):
        x = (1,2,3,4,5,6)
        y = (1,2,3,4,5,6)
        m = random.choice(x)
        l = random.choice(y)
        print("({},{})".format(m,l))


r = Dice()
r.roll()



(2,4)


In [ ]:
# another method

class Dice:
    def roll(self):
        first = random.randint(1,6)
        second = random.randint(1,6)
        return first,second
dice = Dice()
print(dice.roll())

(5, 6)


## **Files and Directories**

In [ ]:
from pathlib import Path
path = Path(".")
print(path.exists())


#if u want to make new directory

# path1 = Path("Files_Directories")
# path1.mkdir()

#when u want to remove directory
#path.rmdir()



True


In [ ]:
path2 = Path()
for file in path2.glob("*.ipynb"):
    print(file)

ch02.ipynb
module.ipynb
Python-1.ipynb


In [ ]:
path3 = Path()
for file in path3.glob("*"):
    print(file)

.ipynb_checkpoints
ch02.ipynb
Files_Directories
module.ipynb
Python-1.ipynb


## **Working with spreadsheet**

In [ ]:
import openpyxl as xl
from openpyxl.chart import BarChart,Reference

# Here openpyxl -> package , chart -> module , BarChart -> class
#instead of passing a file name ->  we can use function and store the path in "filename" variable and pass as argument to function

wb = xl.load_workbook(r'C:\Users\Hritik Jaiswal\Downloads\Spreadsheet\transactions.xlsx')
sheet = wb['Sheet1']


#method to get a cell

cell = sheet['a1']
#another method ->   cell = sheet.cell(1,1)

print(cell.value)
#print max row
print(sheet.max_row)

transaction_id
4


In [ ]:
#we have to modify value of the cell and store into another excel file

for row in range(2,sheet.max_row+1):
    cell = sheet.cell(row,3)  # column is 3
    print(cell.value)
    corrected_value = cell.value * 0.9

    #now we have to place a corrected value into anther column
    corrected_value_cell = sheet.cell(row,4)  #add corrected value into the 4 column

    corrected_value_cell.value = corrected_value
#Excersice

# u have to create a bar graph in excel


values = Reference(sheet,

          min_row=2,max_row = sheet.max_row,

          min_col = 4 , max_col = 4
         )

chart = BarChart()
chart.add_data(values)
sheet.add_chart(chart, 'f2')


wb.save("transaction2.xlsx")



5.95
6.95
7.95


## **Machine learning**

### Steps :

                    1) Import the Data
                    2) clean the Data
                    3) split the Data into training/test sets
                    4) create a model
                    5) train the model
                    6) make prediction
                    7) Evaluate and Improve


In [ ]:
#Importing a data set
import pandas as pd
df = pd.read_csv('vgsales.csv')
df.shape

(16598, 11)

In [ ]:
df.describe()

Rank          Year      NA_Sales      EU_Sales      JP_Sales  \
count  16598.000000  16327.000000  16598.000000  16598.000000  16598.000000   
mean    8300.605254   2006.406443      0.264667      0.146652      0.077782   
std     4791.853933      5.828981      0.816683      0.505351      0.309291   
min        1.000000   1980.000000      0.000000      0.000000      0.000000   
25%     4151.250000   2003.000000      0.000000      0.000000      0.000000   
50%     8300.500000   2007.000000      0.080000      0.020000      0.000000   
75%    12449.750000   2010.000000      0.240000      0.110000      0.040000   
max    16600.000000   2020.000000     41.490000     29.020000     10.220000   

        Other_Sales  Global_Sales  
count  16598.000000  16598.000000  
mean       0.048063      0.537441  
std        0.188588      1.555028  
min        0.000000      0.010000  
25%        0.000000      0.060000  
50%        0.010000      0.170000  
75%        0.040000      0.470000  
max       10.570000     82.740000

In [ ]:
df.values

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

## **Real world problem**

Recommend various music albums thier likely to buy based on age and gender


## **Importing Data**

In [ ]:
import pandas as pd

data = pd.read_csv('music.csv')
data


age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [ ]:
data.describe()

age     gender
count  18.000000  18.000000
mean   27.944444   0.500000
std     5.127460   0.514496
min    20.000000   0.000000
25%    25.000000   0.000000
50%    28.000000   0.500000
75%    31.000000   1.000000
max    37.000000   1.000000

In [ ]:
# we will create two input data set that will be 'age' and 'gender'
# we will pass 'age' and 'gender' and based on the input we predict the output
# output will be stored in 'genre'

X = data.drop(columns=['genre'])

Y = data['genre']


## **Learning and Predicting**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
# takes two attributes 1. input dataset 2. output dataset
model.fit(X,Y)


#let make a prediction by passing input Here 22 is age and 0 is female

prediction = model.predict([[22,0],[25,1]])
prediction



array(['Dance', 'HipHop'], dtype=object)

## **Calculating the Accuracy**

In [ ]:
# for calculating the accuracy we need to test and train the model
# generally 70-80% data need to training and 20-30% for testing

from sklearn.model_selection import train_test_split

# Here we use 20% for testing and check with respect to the predicted value
# the function will return 4 tuple we have to get that result into a variable

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.5)
print(X_train)
model.fit(X_train,Y_train)

# we pass input as X_test in attribute
prediction = model.predict(X_test)

# now to check accurancy we have to compair the prediction with y_test()
from sklearn.metrics import accuracy_score

score = accuracy_score(Y_test,prediction)
print("Accuracy is : {}".format(score))

#every time we run are model accuracy will be changing

    age  gender
0    20       1
3    26       1
5    30       1
6    31       1
12   26       0
9    20       0
11   25       0
2    25       1
10   21       0
Accuracy is : 0.6666666666666666


## **Model Persistance**


for training model again again takes lot of time instead
we can save the trained model in one joblib file

run these piece of code after applying model i.e after :

        model = DecisionTreeClassifier()

        from sklearn.externals import joblib
        joblib.dump(model,'model-recommender.joblib')

after runing these commment the trained model syntax and and then direclty load

        joblib.load('model-recommender.joblib')


## **Visualizing a Decision Tree**


In [ ]:
# u can see a graph i.e decision tree on visual studio code
# by clicking a sidebar preview button

from sklearn import tree
tree.export_graphviz(model,
                    out_file = "music-recommender.dot",
                    class_names = sorted(Y.unique()),
                    label = 'all',
                    rounded =True ,
                    filled= True
                    )

